In [1]:
import seaborn as sns
df=sns.load_dataset('iris')

In [2]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
df.shape

(150, 5)

In [4]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [6]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [86]:
df.describe(include='object').T  ##Transpose

        count unique     top freq
species   150      3  setosa   50

In [7]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [9]:
df.loc[0]

sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object

In [10]:
df.loc[0,['sepal_length']]

sepal_length    5.1
Name: 0, dtype: object

In [18]:
df.loc[:10,['sepal_length','petal_length']]

    sepal_length  petal_length
0            5.1           1.4
1            4.9           1.4
2            4.7           1.3
3            4.6           1.5
4            5.0           1.4
5            5.4           1.7
6            4.6           1.4
7            5.0           1.5
8            4.4           1.4
9            4.9           1.5
10           5.4           1.5

In [21]:
df.iloc[:3,:3]

   sepal_length  sepal_width  petal_length
0           5.1          3.5           1.4
1           4.9          3.0           1.4
2           4.7          3.2           1.3

In [23]:
df.iloc[::3]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
6             4.6          3.4           1.4          0.3      setosa
9             4.9          3.1           1.5          0.1      setosa
12            4.8          3.0           1.4          0.1      setosa
15            5.7          4.4           1.5          0.4      setosa
18            5.7          3.8           1.7          0.3      setosa
21            5.1          3.7           1.5          0.4      setosa
24            4.8          3.4           1.9          0.2      setosa
27            5.2          3.5           1.5          0.2      setosa
30            4.8          3.1           1.6          0.2      setosa
33            5.5          4.2           1.4          0.2      setosa
36            5.5          3.5           1.3          0.2      setosa
39            5.1          3.4           1.5          0.2      setosa
42            4.4          3.2           1.3          0.2      setosa
45            4.8          3.0           1.4          0.3      setosa
48            5.3          3.7           1.5          0.2      setosa
51            6.4          3.2           4.5          1.5  versicolor
54            6.5          2.8           4.6          1.5  versicolor
57            4.9          2.4           3.3          1.0  versicolor
60            5.0          2.0           3.5          1.0  versicolor
63            6.1          2.9           4.7          1.4  versicolor
66            5.6          3.0           4.5          1.5  versicolor
69            5.6          2.5           3.9          1.1  versicolor
72            6.3          2.5           4.9          1.5  versicolor
75            6.6          3.0           4.4          1.4  versicolor
78            6.0          2.9           4.5          1.5  versicolor
81            5.5          2.4           3.7          1.0  versicolor
84            5.4          3.0           4.5          1.5  versicolor
87            6.3          2.3           4.4          1.3  versicolor
90            5.5          2.6           4.4          1.2  versicolor
93            5.0          2.3           3.3          1.0  versicolor
96            5.7          2.9           4.2          1.3  versicolor
99            5.7          2.8           4.1          1.3  versicolor
102           7.1          3.0           5.9          2.1   virginica
105           7.6          3.0           6.6          2.1   virginica
108           6.7          2.5           5.8          1.8   virginica
111           6.4          2.7           5.3          1.9   virginica
114           5.8          2.8           5.1          2.4   virginica
117           7.7          3.8           6.7          2.2   virginica
120           6.9          3.2           5.7          2.3   virginica
123           6.3          2.7           4.9          1.8   virginica
126           6.2          2.8           4.8          1.8   virginica
129           7.2          3.0           5.8          1.6   virginica
132           6.4          2.8           5.6          2.2   virginica
135           7.7          3.0           6.1          2.3   virginica
138           6.0          3.0           4.8          1.8   virginica
141           6.9          3.1           5.1          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
147           6.5          3.0           5.2          2.0   virginica

In [28]:
df.iloc[5:11,1:4]

    sepal_width  petal_length  petal_width
5           3.9           1.7          0.4
6           3.4           1.4          0.3
7           3.4           1.5          0.2
8           2.9           1.4          0.2
9           3.1           1.5          0.1
10          3.7           1.5          0.2

In [37]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [36]:
df.iloc[5:11,1::2]

    sepal_width  petal_width
5           3.9          0.4
6           3.4          0.3
7           3.4          0.2
8           2.9          0.2
9           3.1          0.1
10          3.7          0.2

In [44]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [45]:
df.iloc[5:6, 0:5:4]

   sepal_length species
5           5.4  setosa

In [46]:
df.iloc[0:3,0:4:3]

   sepal_length  petal_width
0           5.1          0.2
1           4.9          0.2
2           4.7          0.2

In [49]:
df.iloc[-4:-20:-3]

     sepal_length  sepal_width  petal_length  petal_width    species
146           6.3          2.5           5.0          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
140           6.7          3.1           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
134           6.1          2.6           5.6          1.4  virginica
131           7.9          3.8           6.4          2.0  virginica

**Condition Based retrieval**

In [58]:
df[df['petal_width']>2]

     sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
102           7.1          3.0           5.9          2.1  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
109           7.2          3.6           6.1          2.5  virginica
112           6.8          3.0           5.5          2.1  virginica
114           5.8          2.8           5.1          2.4  virginica
115           6.4          3.2           5.3          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
120           6.9          3.2           5.7          2.3  virginica
124           6.7          3.3           5.7          2.1  virginica
128           6.4          2.8           5.6          2.1  virginica
132           6.4          2.8           5.6          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
148           6.2          3.4           5.4          2.3  virginica

In [59]:
df['sepal_length']>5.2

0      False
1      False
2      False
3      False
4      False
       ...
145     True
146     True
147     True
148     True
149     True
Name: sepal_length, Length: 150, dtype: bool

In [60]:
df[df['sepal_length']>5.2]

     sepal_length  sepal_width  petal_length  petal_width    species
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[105 rows x 5 columns]

In [61]:
df.query('sepal_length>5')

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[118 rows x 5 columns]

In [72]:
c= df.loc[:5,'species']=='setosa'
c

0    True
1    True
2    True
3    True
4    True
5    True
Name: species, dtype: bool

In [73]:
df.nunique()

sepal_length    35
sepal_width     23
petal_length    43
petal_width     22
species          3
dtype: int64

In [79]:
df.petal_length.nsmallest()

22    1.0
13    1.1
14    1.2
35    1.2
2     1.3
Name: petal_length, dtype: float64

In [80]:
df.petal_length.nsmallest(2)

22    1.0
13    1.1
Name: petal_length, dtype: float64

In [77]:
df.sepal_length.nlargest()

131    7.9
117    7.7
118    7.7
122    7.7
135    7.7
Name: sepal_length, dtype: float64

**Data Cleaning**

In [87]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64