### **Pandas**
- This notebook is for practicing pandas library
- Almost all the pandas operations will be here

In [457]:
import warnings
warnings.filterwarnings('ignore')

In [458]:
#importing pandas library
import pandas as pd

In [459]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [460]:
pd.__version__

'2.3.1'

In [461]:
print(pd.__doc__)

pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

**Series**

In [462]:
age = [20,25,23,30,41,12,10,15,60]
index = ['a','b','c','d','e','f','g','h','i']

series = pd.Series(data=age, index=index, name='Series')
series

a    20
b    25
c    23
d    30
e    41
f    12
g    10
h    15
i    60
Name: Series, dtype: int64

**Data Frame**

In [463]:
print(pd.DataFrame.__doc__)

Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

    .. versionchanged:: 1.3.0

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
...                    columns=['a', 'b', 'c'])
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
>>> df3 = pd.DataFrame(data, columns=['c', 'a'])
...
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3

In [464]:
data ={'Name': ['Karthik', 'Virat', 'Sachin', 'Hazlewood', 'Krunal'],
        'Age': [28, 18, 13, 62, 50],
        'Department': ['HR', 'Admin', 'AI', 'Admin', 'HR'],
        'Salary': [4000,  5000, 4500, 6000, 4800]

}

df= pd.DataFrame(data)

In [465]:
df= pd.DataFrame(data=data)
df

        Name  Age Department  Salary
0    Karthik   28         HR    4000
1      Virat   18      Admin    5000
2     Sachin   13         AI    4500
3  Hazlewood   62      Admin    6000
4     Krunal   50         HR    4800

In [466]:
df.shape

(5, 4)

In [467]:
df.shape[0]  ##Rows

5

In [468]:
df.shape[1]  #Columns

4

In [469]:
df.dtypes

Name          object
Age            int64
Department    object
Salary         int64
dtype: object

In [470]:
df.columns

Index(['Name', 'Age', 'Department', 'Salary'], dtype='object')

In [471]:
df.columns[:3]

Index(['Name', 'Age', 'Department'], dtype='object')

In [472]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Salary      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [473]:
for col in df.columns:
    print(f"{col} : {df[col].unique()}")

Name : ['Karthik' 'Virat' 'Sachin' 'Hazlewood' 'Krunal']
Age : [28 18 13 62 50]
Department : ['HR' 'Admin' 'AI']
Salary : [4000 5000 4500 6000 4800]

In [474]:
df.nunique()

Name          5
Age           5
Department    3
Salary        5
dtype: int64

In [475]:
df.Age.nsmallest()

2    13
1    18
0    28
4    50
3    62
Name: Age, dtype: int64

In [476]:
df.Age.nlargest()

3    62
4    50
0    28
1    18
2    13
Name: Age, dtype: int64

In [477]:
df.describe()

             Age       Salary
count   5.000000     5.000000
mean   34.200000  4860.000000
std    21.052316   740.270221
min    13.000000  4000.000000
25%    18.000000  4500.000000
50%    28.000000  4800.000000
75%    50.000000  5000.000000
max    62.000000  6000.000000

In [478]:
df.describe().T   ##Transpose

        count    mean         std     min     25%     50%     75%     max
Age       5.0    34.2   21.052316    13.0    18.0    28.0    50.0    62.0
Salary    5.0  4860.0  740.270221  4000.0  4500.0  4800.0  5000.0  6000.0

In [479]:
df.describe(include='object').T

           count unique      top freq
Name           5      5  Karthik    1
Department     5      3       HR    2

**Data Manipulation**

In [480]:
df.head()

        Name  Age Department  Salary
0    Karthik   28         HR    4000
1      Virat   18      Admin    5000
2     Sachin   13         AI    4500
3  Hazlewood   62      Admin    6000
4     Krunal   50         HR    4800

In [481]:
df.tail()

        Name  Age Department  Salary
0    Karthik   28         HR    4000
1      Virat   18      Admin    5000
2     Sachin   13         AI    4500
3  Hazlewood   62      Admin    6000
4     Krunal   50         HR    4800

In [482]:
## Selecting columns
## Single column
df['Name']

0      Karthik
1        Virat
2       Sachin
3    Hazlewood
4       Krunal
Name: Name, dtype: object

In [483]:
## Selecting multiple columns
df[['Name', 'Age']]

        Name  Age
0    Karthik   28
1      Virat   18
2     Sachin   13
3  Hazlewood   62
4     Krunal   50

In [484]:
## Using dot notation
df.Age

0    28
1    18
2    13
3    62
4    50
Name: Age, dtype: int64

In [485]:
col = df.columns[:4]
df[col]

        Name  Age Department  Salary
0    Karthik   28         HR    4000
1      Virat   18      Admin    5000
2     Sachin   13         AI    4500
3  Hazlewood   62      Admin    6000
4     Krunal   50         HR    4800

In [486]:
df[1:3]

     Name  Age Department  Salary
1   Virat   18      Admin    5000
2  Sachin   13         AI    4500

In [487]:
df[1:10:2]

        Name  Age Department  Salary
1      Virat   18      Admin    5000
3  Hazlewood   62      Admin    6000

In [488]:
## To select Rows
## loc:- label based
df.loc[0]

Name          Karthik
Age                28
Department         HR
Salary           4000
Name: 0, dtype: object

In [489]:
df.loc[0:2]

      Name  Age Department  Salary
0  Karthik   28         HR    4000
1    Virat   18      Admin    5000
2   Sachin   13         AI    4500

In [490]:
# Select rows 1 to 3 and specific columns
df.loc[1:3, ['Name', 'Salary']]

        Name  Salary
1      Virat    5000
2     Sachin    4500
3  Hazlewood    6000

In [491]:
## iloc:- Position Based
df.iloc[0]

Name          Karthik
Age                28
Department         HR
Salary           4000
Name: 0, dtype: object

In [492]:
df.iloc[0:3]

      Name  Age Department  Salary
0  Karthik   28         HR    4000
1    Virat   18      Admin    5000
2   Sachin   13         AI    4500

In [493]:
## Let's see for iris data
import seaborn as sns
df1= sns.load_dataset('iris')

In [494]:
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [495]:
df1.loc[0]

sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object

In [496]:
df1.loc[0:2]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [497]:
df1.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [498]:
df1.loc[1:3, ['sepal_length', 'sepal_width']]

   sepal_length  sepal_width
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1

In [499]:
df1.iloc[0:5]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [500]:
df1.iloc[::2]

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
6             4.6          3.4           1.4          0.3     setosa
8             4.4          2.9           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
140           6.7          3.1           5.6          2.4  virginica
142           5.8          2.7           5.1          1.9  virginica
144           6.7          3.3           5.7          2.5  virginica
146           6.3          2.5           5.0          1.9  virginica
148           6.2          3.4           5.4          2.3  virginica

[75 rows x 5 columns]

In [501]:
df1.iloc[::3]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
6             4.6          3.4           1.4          0.3      setosa
9             4.9          3.1           1.5          0.1      setosa
12            4.8          3.0           1.4          0.1      setosa
15            5.7          4.4           1.5          0.4      setosa
18            5.7          3.8           1.7          0.3      setosa
21            5.1          3.7           1.5          0.4      setosa
24            4.8          3.4           1.9          0.2      setosa
27            5.2          3.5           1.5          0.2      setosa
30            4.8          3.1           1.6          0.2      setosa
33            5.5          4.2           1.4          0.2      setosa
36            5.5          3.5           1.3          0.2      setosa
39            5.1          3.4           1.5          0.2      setosa
42            4.4          3.2           1.3          0.2      setosa
45            4.8          3.0           1.4          0.3      setosa
48            5.3          3.7           1.5          0.2      setosa
51            6.4          3.2           4.5          1.5  versicolor
54            6.5          2.8           4.6          1.5  versicolor
57            4.9          2.4           3.3          1.0  versicolor
60            5.0          2.0           3.5          1.0  versicolor
63            6.1          2.9           4.7          1.4  versicolor
66            5.6          3.0           4.5          1.5  versicolor
69            5.6          2.5           3.9          1.1  versicolor
72            6.3          2.5           4.9          1.5  versicolor
75            6.6          3.0           4.4          1.4  versicolor
78            6.0          2.9           4.5          1.5  versicolor
81            5.5          2.4           3.7          1.0  versicolor
84            5.4          3.0           4.5          1.5  versicolor
87            6.3          2.3           4.4          1.3  versicolor
90            5.5          2.6           4.4          1.2  versicolor
93            5.0          2.3           3.3          1.0  versicolor
96            5.7          2.9           4.2          1.3  versicolor
99            5.7          2.8           4.1          1.3  versicolor
102           7.1          3.0           5.9          2.1   virginica
105           7.6          3.0           6.6          2.1   virginica
108           6.7          2.5           5.8          1.8   virginica
111           6.4          2.7           5.3          1.9   virginica
114           5.8          2.8           5.1          2.4   virginica
117           7.7          3.8           6.7          2.2   virginica
120           6.9          3.2           5.7          2.3   virginica
123           6.3          2.7           4.9          1.8   virginica
126           6.2          2.8           4.8          1.8   virginica
129           7.2          3.0           5.8          1.6   virginica
132           6.4          2.8           5.6          2.2   virginica
135           7.7          3.0           6.1          2.3   virginica
138           6.0          3.0           4.8          1.8   virginica
141           6.9          3.1           5.1          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
147           6.5          3.0           5.2          2.0   virginica

In [502]:
df1.iloc[4:10:1]

   sepal_length  sepal_width  petal_length  petal_width species
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [503]:
## First three rows and first 2 columns
df1.iloc[0:3, 0:2]

   sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2

In [504]:
df1.iloc[0:5:3]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa

In [505]:
df1.iloc[1:5, 1:4]

   sepal_width  petal_length  petal_width
1          3.0           1.4          0.2
2          3.2           1.3          0.2
3          3.1           1.5          0.2
4          3.6           1.4          0.2

In [506]:
df[df['Salary']>4500]

        Name  Age Department  Salary
1      Virat   18      Admin    5000
3  Hazlewood   62      Admin    6000
4     Krunal   50         HR    4800

In [507]:
df1[df1['sepal_length']>5.0]

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[118 rows x 5 columns]

In [508]:
df1[df1['petal_length']>5.0]

     sepal_length  sepal_width  petal_length  petal_width     species
83            6.0          2.7           5.1          1.6  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
110           6.5          3.2           5.1          2.0   virginica
111           6.4          2.7           5.3          1.9   virginica
112           6.8          3.0           5.5          2.1   virginica
114           5.8          2.8           5.1          2.4   virginica
115           6.4          3.2           5.3          2.3   virginica
116           6.5          3.0           5.5          1.8   virginica
117           7.7          3.8           6.7          2.2   virginica
118           7.7          2.6           6.9          2.3   virginica
120           6.9          3.2           5.7          2.3   virginica
122           7.7          2.8           6.7          2.0   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
128           6.4          2.8           5.6          2.1   virginica
129           7.2          3.0           5.8          1.6   virginica
130           7.4          2.8           6.1          1.9   virginica
131           7.9          3.8           6.4          2.0   virginica
132           6.4          2.8           5.6          2.2   virginica
133           6.3          2.8           5.1          1.5   virginica
134           6.1          2.6           5.6          1.4   virginica
135           7.7          3.0           6.1          2.3   virginica
136           6.3          3.4           5.6          2.4   virginica
137           6.4          3.1           5.5          1.8   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
142           5.8          2.7           5.1          1.9   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

In [509]:
df1.query('sepal_length > 5')

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[118 rows x 5 columns]

In [510]:
query_test = df1.query('sepal_length > 5 and species == "setosa"')
print(query_test.head())

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
10           5.4          3.7           1.5          0.2  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa

In [511]:
df1[df1['species'] == 'setosa']

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [512]:
df1[(df1['sepal_length'] > 5) & (df1['species'] == 'virginica')]

     sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
101           5.8          2.7           5.1          1.9  virginica
102           7.1          3.0           5.9          2.1  virginica
103           6.3          2.9           5.6          1.8  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
107           7.3          2.9           6.3          1.8  virginica
108           6.7          2.5           5.8          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
110           6.5          3.2           5.1          2.0  virginica
111           6.4          2.7           5.3          1.9  virginica
112           6.8          3.0           5.5          2.1  virginica
113           5.7          2.5           5.0          2.0  virginica
114           5.8          2.8           5.1          2.4  virginica
115           6.4          3.2           5.3          2.3  virginica
116           6.5          3.0           5.5          1.8  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
119           6.0          2.2           5.0          1.5  virginica
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [513]:
df1[(df1['petal_width'] > 2.5) | (df1['species'] == 'versicolor')]

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

**isin**

In [514]:
df1[df1['species'].isin(['virginica','versicolor'])]

     sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

[100 rows x 5 columns]

In [515]:
## Multi Indexing
employee = [
    ['HR', 'HR', 'IT', 'IT'],
    ['Karthik', 'Kumar', 'Siraj', 'Jithesh']
]
index = pd.MultiIndex.from_arrays(employee, names=('Department', 'Name'))
multi_df = pd.DataFrame({'Salary': [4000, 4200, 5000, 5500]}, index=index)

multi_df

                    Salary
Department Name
HR         Karthik    4000
           Kumar      4200
IT         Siraj      5000
           Jithesh    5500

In [516]:
multi_df.loc['HR']

         Salary
Name
Karthik    4000
Kumar      4200

In [517]:
multi_df.loc[('IT','Siraj')]

Salary    5000
Name: (IT, Siraj), dtype: int64

In [518]:
## Cross section 
multi_df.xs('IT')

         Salary
Name
Siraj      5000
Jithesh    5500

In [519]:
filtered= df1[df1['species'].isin(['setosa', 'virginica'])]
filtered

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[100 rows x 5 columns]

In [520]:
filtered_r= df1[df1['sepal_length'].between(5,6)]
filtered_r

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
7             5.0          3.4           1.5          0.2     setosa
10            5.4          3.7           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
119           6.0          2.2           5.0          1.5  virginica
121           5.6          2.8           4.9          2.0  virginica
138           6.0          3.0           4.8          1.8  virginica
142           5.8          2.7           5.1          1.9  virginica
149           5.9          3.0           5.1          1.8  virginica

[67 rows x 5 columns]

In [521]:
filtered_s= df1[df1['species'].str.contains('vir')]
filtered_s

     sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
101           5.8          2.7           5.1          1.9  virginica
102           7.1          3.0           5.9          2.1  virginica
103           6.3          2.9           5.6          1.8  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
106           4.9          2.5           4.5          1.7  virginica
107           7.3          2.9           6.3          1.8  virginica
108           6.7          2.5           5.8          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
110           6.5          3.2           5.1          2.0  virginica
111           6.4          2.7           5.3          1.9  virginica
112           6.8          3.0           5.5          2.1  virginica
113           5.7          2.5           5.0          2.0  virginica
114           5.8          2.8           5.1          2.4  virginica
115           6.4          3.2           5.3          2.3  virginica
116           6.5          3.0           5.5          1.8  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
119           6.0          2.2           5.0          1.5  virginica
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [522]:
## To use isna() Im making first row species value as None
df1.loc[0, 'species']=None
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2    None
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [523]:
missing= df1[df1['species'].isna()]
missing

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2    None

In [524]:
value= df1.at[1, 'species']
value

'setosa'

In [525]:
value1= df1.iat[1, 0]
value1

np.float64(4.9)

In [526]:
result= df1['sepal_length'].where(df1['sepal_length']>5)
result

0      5.1
1      NaN
2      NaN
3      NaN
4      NaN
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [527]:
result1= df1['sepal_length'].mask(df1['sepal_length']>5)
result1

0      NaN
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    NaN
146    NaN
147    NaN
148    NaN
149    NaN
Name: sepal_length, Length: 150, dtype: float64

**Modifying Values**

In [528]:
data1 = {
    'Name': [
        'Virat Kohli', 'Rohit Sharma', 'MS Dhoni', 'KL Rahul',
        'Hardik Pandya', 'Jasprit Bumrah', 'Ravindra Jadeja',
        'Shubman Gill', 'Rishabh Pant', 'Suryakumar Yadav',
        'Rishabh Pant', 'Suryakumar Yadav', 'Ravindra Jadeja', 'Shubman Gill'
    ],
    
    'Age': [
        35, 36, 42, 32,
        31, 30, None,
        25, 27, 33,
        27, 33, 34, 25
    ],
    
    'City': [
        'Mumbai', 'Delhi', 'Chennai', 'Bengaluru',
        'Ahmedabad', 'Madhya Pradesh', 'Pune',
        'Kolkata', 'Delhi', 'Mumbai',
        'Delhi', 'Mumbai', 'Pune', 'Kolkata'
    ],
    
    'Salary': [
        1850000, 1750000, 2100000, 1500000,
        1600000, 1700000, 1550000,
        1400000, 1450000, 1650000,
        1450000, 1650000, 1550000, None
    ],
    
    'Date': [
        '2024-06-01', '2024-06-02', '2024-06-03', '2024-06-04',
        '2024-06-05', '2024-06-06', '2024-06-07', '2024-06-08',
        '2024-06-09', '2024-06-10', '2024-06-09', '2024-06-10',
        '2024-06-07', '2024-06-08'
    ],
    
    'Category': [
        'X', 'Y', 'Z', 'X',
        'Y', 'X', 'Z', 'Y',
        'X', 'Y', 'X', 'Y',
        None, 'Y'
    ]
}

In [529]:
df2 = pd.DataFrame(data=data1)
df2

                Name   Age            City     Salary        Date Category
0        Virat Kohli  35.0          Mumbai  1850000.0  2024-06-01        X
1       Rohit Sharma  36.0           Delhi  1750000.0  2024-06-02        Y
2           MS Dhoni  42.0         Chennai  2100000.0  2024-06-03        Z
3           KL Rahul  32.0       Bengaluru  1500000.0  2024-06-04        X
4      Hardik Pandya  31.0       Ahmedabad  1600000.0  2024-06-05        Y
5     Jasprit Bumrah  30.0  Madhya Pradesh  1700000.0  2024-06-06        X
6    Ravindra Jadeja   NaN            Pune  1550000.0  2024-06-07        Z
7       Shubman Gill  25.0         Kolkata  1400000.0  2024-06-08        Y
8       Rishabh Pant  27.0           Delhi  1450000.0  2024-06-09        X
9   Suryakumar Yadav  33.0          Mumbai  1650000.0  2024-06-10        Y
10      Rishabh Pant  27.0           Delhi  1450000.0  2024-06-09        X
11  Suryakumar Yadav  33.0          Mumbai  1650000.0  2024-06-10        Y
12   Ravindra Jadeja  34.0            Pune  1550000.0  2024-06-07     None
13      Shubman Gill  25.0         Kolkata        NaN  2024-06-08        Y

In [530]:
df2['Name'][2]

'MS Dhoni'

In [531]:
print(f"Before Modifying : {df2['Name'][2]}")

df2['Name'][2] = 'Dhoni'

print(f"After Modifying : {df2['Name'][2]}")

Before Modifying : MS Dhoni
After Modifying : Dhoni

In [532]:
df2.loc[2]

Name             Dhoni
Age               42.0
City           Chennai
Salary       2100000.0
Date        2024-06-03
Category             Z
Name: 2, dtype: object

**String methods**

In [533]:
df2[df2['City'].str.contains('chennai', case=False)]

    Name   Age     City     Salary        Date Category
2  Dhoni  42.0  Chennai  2100000.0  2024-06-03        Z

In [534]:
df2['City'].str.split(' ')

0              [Mumbai]
1               [Delhi]
2             [Chennai]
3           [Bengaluru]
4           [Ahmedabad]
5     [Madhya, Pradesh]
6                [Pune]
7             [Kolkata]
8               [Delhi]
9              [Mumbai]
10              [Delhi]
11             [Mumbai]
12               [Pune]
13            [Kolkata]
Name: City, dtype: object

In [535]:
df2['City'].str.split(' ').str.get(0)

0        Mumbai
1         Delhi
2       Chennai
3     Bengaluru
4     Ahmedabad
5        Madhya
6          Pune
7       Kolkata
8         Delhi
9        Mumbai
10        Delhi
11       Mumbai
12         Pune
13      Kolkata
Name: City, dtype: object

In [536]:
df2[df2['Name'].str.startswith('S')]

                Name   Age     City     Salary        Date Category
7       Shubman Gill  25.0  Kolkata  1400000.0  2024-06-08        Y
9   Suryakumar Yadav  33.0   Mumbai  1650000.0  2024-06-10        Y
11  Suryakumar Yadav  33.0   Mumbai  1650000.0  2024-06-10        Y
13      Shubman Gill  25.0  Kolkata        NaN  2024-06-08        Y

In [537]:
df2[df2['Name'].str.endswith('l')]

            Name   Age       City     Salary        Date Category
3       KL Rahul  32.0  Bengaluru  1500000.0  2024-06-04        X
7   Shubman Gill  25.0    Kolkata  1400000.0  2024-06-08        Y
13  Shubman Gill  25.0    Kolkata        NaN  2024-06-08        Y

In [538]:
df2['City1'] = df2['City'].str.upper()
df2['City1']

0             MUMBAI
1              DELHI
2            CHENNAI
3          BENGALURU
4          AHMEDABAD
5     MADHYA PRADESH
6               PUNE
7            KOLKATA
8              DELHI
9             MUMBAI
10             DELHI
11            MUMBAI
12              PUNE
13           KOLKATA
Name: City1, dtype: object

In [539]:
df2['Name1'] = df2['Name'].str.lower()
df2['Name1']

0          virat kohli
1         rohit sharma
2                dhoni
3             kl rahul
4        hardik pandya
5       jasprit bumrah
6      ravindra jadeja
7         shubman gill
8         rishabh pant
9     suryakumar yadav
10        rishabh pant
11    suryakumar yadav
12     ravindra jadeja
13        shubman gill
Name: Name1, dtype: object

In [540]:
df2['Name1'] = df2['Name'].str.capitalize()
df2['Name1']

0          Virat kohli
1         Rohit sharma
2                Dhoni
3             Kl rahul
4        Hardik pandya
5       Jasprit bumrah
6      Ravindra jadeja
7         Shubman gill
8         Rishabh pant
9     Suryakumar yadav
10        Rishabh pant
11    Suryakumar yadav
12     Ravindra jadeja
13        Shubman gill
Name: Name1, dtype: object

In [541]:
df2['Name'].str.count('Hannah').sum()

np.int64(0)

In [542]:
df2['Name'].add(' Mr')

0          Virat Kohli Mr
1         Rohit Sharma Mr
2                Dhoni Mr
3             KL Rahul Mr
4        Hardik Pandya Mr
5       Jasprit Bumrah Mr
6      Ravindra Jadeja Mr
7         Shubman Gill Mr
8         Rishabh Pant Mr
9     Suryakumar Yadav Mr
10        Rishabh Pant Mr
11    Suryakumar Yadav Mr
12     Ravindra Jadeja Mr
13        Shubman Gill Mr
Name: Name, dtype: object

In [543]:
df2['City'] = df2['City'].str.replace('Bengaluru','Karnataka')
df2['City']

0             Mumbai
1              Delhi
2            Chennai
3          Karnataka
4          Ahmedabad
5     Madhya Pradesh
6               Pune
7            Kolkata
8              Delhi
9             Mumbai
10             Delhi
11            Mumbai
12              Pune
13           Kolkata
Name: City, dtype: object

### **Data Cleaning**

In [544]:
data = pd.DataFrame({
    'A': [10, 22, None, 45, None, 67, 78, 10, 999],
    'B': [5, None, 15, None, 25, None, 300, 5, 5]
})

data

       A      B
0   10.0    5.0
1   22.0    NaN
2    NaN   15.0
3   45.0    NaN
4    NaN   25.0
5   67.0    NaN
6   78.0  300.0
7   10.0    5.0
8  999.0    5.0

In [545]:
##Missing values
data.isnull().sum()

A    2
B    3
dtype: int64

In [546]:
data.isna().sum()

A    2
B    3
dtype: int64

In [547]:
data.notnull().sum()

A    7
B    6
dtype: int64

In [548]:
data.notna().sum()

A    7
B    6
dtype: int64

In [549]:
##Finding duplicates
data.duplicated().sum()

np.int64(1)

In [550]:
##Finding Outlier
def find_outlier(df, columns):
    outlier_indices = set()
    
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lf = Q1 - 1.5 * IQR
        uf = Q3 + 1.5 * IQR
        col_outliers = df[(df[col] < lf) | (df[col] > uf)]
        outlier_indices.update(col_outliers.index)
        
    return df.loc[list(outlier_indices)]

outliers = find_outlier(data, ['A', 'B'])
print(outliers)

       A      B
8  999.0    5.0
6   78.0  300.0

**Handling missing values**

In [551]:
##In a specific column
dropna = data.dropna()
dropna

       A      B
0   10.0    5.0
6   78.0  300.0
7   10.0    5.0
8  999.0    5.0

In [552]:
round(data['A'].mean(), 2)

np.float64(175.86)

In [553]:
data['A'].fillna(round(data['A'].mean(), 2))

0     10.00
1     22.00
2    175.86
3     45.00
4    175.86
5     67.00
6     78.00
7     10.00
8    999.00
Name: A, dtype: float64

In [554]:
data['B'].fillna(round(data['B'].mean(), 2))

0      5.00
1     59.17
2     15.00
3     59.17
4     25.00
5     59.17
6    300.00
7      5.00
8      5.00
Name: B, dtype: float64

In [555]:
data['A']

0     10.0
1     22.0
2      NaN
3     45.0
4      NaN
5     67.0
6     78.0
7     10.0
8    999.0
Name: A, dtype: float64

In [556]:
##Replace with average of surrouding values
data['A'].interpolate()

0     10.0
1     22.0
2     33.5
3     45.0
4     56.0
5     67.0
6     78.0
7     10.0
8    999.0
Name: A, dtype: float64

**Handling Duplicate Values**

In [557]:
data[data.duplicated()]

      A    B
7  10.0  5.0

In [558]:
data.drop_duplicates().reset_index(drop=True)

       A      B
0   10.0    5.0
1   22.0    NaN
2    NaN   15.0
3   45.0    NaN
4    NaN   25.0
5   67.0    NaN
6   78.0  300.0
7  999.0    5.0

**Handling the outlier**

In [559]:
##Dropping
data.dropna(inplace=True)
data

       A      B
0   10.0    5.0
6   78.0  300.0
7   10.0    5.0
8  999.0    5.0

In [560]:
##Finding Outlier
def remove_outlier(df, columns):

    Cleaned_df = df.copy()
    
    for col in columns:
        Q1 = Cleaned_df[col].quantile(0.25)
        Q3 = Cleaned_df[col].quantile(0.75)
        IQR = Q3 - Q1
        lf = Q1 - 1.5 * IQR
        uf = Q3 + 1.5 * IQR
        
        Cleaned_df = Cleaned_df[(Cleaned_df[col] >= lf) & (Cleaned_df[col] <= uf)]
        
    return Cleaned_df

outliers = remove_outlier(data, ['A', 'B'])
print(outliers)

      A      B
0  10.0    5.0
6  78.0  300.0
7  10.0    5.0

In [561]:
Q1 = data['B'].quantile(0.25)
Q1

np.float64(5.0)

In [562]:
Q3 = data['B'].quantile(0.75)
Q3

np.float64(78.75)

In [563]:
IQR = Q3-Q1
lf = Q1 - 1.5 * IQR
lf

np.float64(-105.625)

In [564]:
uf = Q3 + 1.5 * IQR
uf

np.float64(189.375)

In [565]:
import numpy as np

def log_transformation(df, columns):
    
    tranform_df = df.copy()

    for col in columns:
        tranform_df[col] = np.log1p(tranform_df[col]) 
    return tranform_df

log = log_transformation(data, ['A', 'B'])
log

          A         B
0  2.397895  1.791759
6  4.369448  5.707110
7  2.397895  1.791759
8  6.907755  1.791759

In [566]:
df2

,Name,Age,City,Salary,Date,Category,City1,Name1
0,Virat Kohli,35.0,Mumbai,1850000.0,2024-06-01,X,MUMBAI,Virat kohli
1,Rohit Sharma,36.0,Delhi,1750000.0,2024-06-02,Y,DELHI,Rohit sharma
2,Dhoni,42.0,Chennai,2100000.0,2024-06-03,Z,CHENNAI,Dhoni
3,KL Rahul,32.0,Karnataka,1500000.0,2024-06-04,X,BENGALURU,Kl rahul
4,Hardik Pandya,31.0,Ahmedabad,1600000.0,2024-06-05,Y,AHMEDABAD,Hardik pandya
5,Jasprit Bumrah,30.0,Madhya Pradesh,1700000.0,2024-06-06,X,MADHYA PRADESH,Jasprit bumrah
6,Ravindra Jadeja,NaN,Pune,1550000.0,2024-06-07,Z,PUNE,Ravindra jadeja
7,Shubman Gill,25.0,Kolkata,1400000.0,2024-06-08,Y,KOLKATA,Shubman gill
8,Rishabh Pant,27.0,Delhi,1450000.0,2024-06-09,X,DELHI,Rishabh pant
9,Suryakumar Yadav,33.0,Mumbai,1650000.0,2024-06-10,Y,MUMBAI,Suryakumar yadav
10,Rishabh Pant,27.0,Delhi,1450000.0,2024-06-09,X,DELHI,Rishabh pant
11,Suryakumar Yadav,33.0,Mumbai,1650000.0,2024-06-10,Y,MUMBAI,Suryakumar yadav
12,Ravindra Jadeja,34.0,Pune,1550000.0,2024-06-07,None,PUNE,Ravindra jadeja
13,Shubman Gill,25.0,Kolkata,NaN,2024-06-08,Y,KOLKATA,Shubman gill

In [567]:
df2.isnull().sum()

Name        0
Age         1
City        0
Salary      1
Date        0
Category    1
City1       0
Name1       0
dtype: int64

In [568]:
df2.duplicated().sum()

np.int64(2)

In [569]:
df2['Age'].fillna(round(df2['Age'].mean(), 2), inplace=True)
df2['Salary'].fillna(round(df2['Salary'].mean(), 2), inplace=True)
df2['Category'].fillna(df2['Category'].mode()[0], inplace = True)

In [570]:
df2.drop_duplicates(inplace=True)

In [571]:
df2

,Name,Age,City,Salary,Date,Category,City1,Name1
0,Virat Kohli,35.00,Mumbai,1850000.00,2024-06-01,X,MUMBAI,Virat kohli
1,Rohit Sharma,36.00,Delhi,1750000.00,2024-06-02,Y,DELHI,Rohit sharma
2,Dhoni,42.00,Chennai,2100000.00,2024-06-03,Z,CHENNAI,Dhoni
3,KL Rahul,32.00,Karnataka,1500000.00,2024-06-04,X,BENGALURU,Kl rahul
4,Hardik Pandya,31.00,Ahmedabad,1600000.00,2024-06-05,Y,AHMEDABAD,Hardik pandya
5,Jasprit Bumrah,30.00,Madhya Pradesh,1700000.00,2024-06-06,X,MADHYA PRADESH,Jasprit bumrah
6,Ravindra Jadeja,31.54,Pune,1550000.00,2024-06-07,Z,PUNE,Ravindra jadeja
7,Shubman Gill,25.00,Kolkata,1400000.00,2024-06-08,Y,KOLKATA,Shubman gill
8,Rishabh Pant,27.00,Delhi,1450000.00,2024-06-09,X,DELHI,Rishabh pant
9,Suryakumar Yadav,33.00,Mumbai,1650000.00,2024-06-10,Y,MUMBAI,Suryakumar yadav
12,Ravindra Jadeja,34.00,Pune,1550000.00,2024-06-07,Y,PUNE,Ravindra jadeja
13,Shubman Gill,25.00,Kolkata,1630769.23,2024-06-08,Y,KOLKATA,Shubman gill

In [572]:
df2= df2.reset_index(drop=True)

### **Data Transformation**

In [573]:
df2.rename(columns={'Name':"Full Name"}, inplace =True)

In [574]:
df2['Age'] = df2['Age'].astype('int')

In [575]:
df2['City'].replace({"Mumbai":"Maharashtra"}, inplace=True)

In [576]:
df2

,Full Name,Age,City,Salary,Date,Category,City1,Name1
0,Virat Kohli,35,Maharashtra,1850000.00,2024-06-01,X,MUMBAI,Virat kohli
1,Rohit Sharma,36,Delhi,1750000.00,2024-06-02,Y,DELHI,Rohit sharma
2,Dhoni,42,Chennai,2100000.00,2024-06-03,Z,CHENNAI,Dhoni
3,KL Rahul,32,Karnataka,1500000.00,2024-06-04,X,BENGALURU,Kl rahul
4,Hardik Pandya,31,Ahmedabad,1600000.00,2024-06-05,Y,AHMEDABAD,Hardik pandya
5,Jasprit Bumrah,30,Madhya Pradesh,1700000.00,2024-06-06,X,MADHYA PRADESH,Jasprit bumrah
6,Ravindra Jadeja,31,Pune,1550000.00,2024-06-07,Z,PUNE,Ravindra jadeja
7,Shubman Gill,25,Kolkata,1400000.00,2024-06-08,Y,KOLKATA,Shubman gill
8,Rishabh Pant,27,Delhi,1450000.00,2024-06-09,X,DELHI,Rishabh pant
9,Suryakumar Yadav,33,Maharashtra,1650000.00,2024-06-10,Y,MUMBAI,Suryakumar yadav
10,Ravindra Jadeja,34,Pune,1550000.00,2024-06-07,Y,PUNE,Ravindra jadeja
11,Shubman Gill,25,Kolkata,1630769.23,2024-06-08,Y,KOLKATA,Shubman gill

In [577]:
def Catgorize(col):
    if col < 18:
        return "Young"
    elif col < 35:
        return "Adult"
    elif col < 55:
        return "Middle Age"
    else:
        return "Senior"

In [578]:
df2['Age Category'] = df2['Age'].apply(Catgorize)
df2

,Full Name,Age,City,Salary,Date,Category,City1,Name1,Age Category
0,Virat Kohli,35,Maharashtra,1850000.00,2024-06-01,X,MUMBAI,Virat kohli,Middle Age
1,Rohit Sharma,36,Delhi,1750000.00,2024-06-02,Y,DELHI,Rohit sharma,Middle Age
2,Dhoni,42,Chennai,2100000.00,2024-06-03,Z,CHENNAI,Dhoni,Middle Age
3,KL Rahul,32,Karnataka,1500000.00,2024-06-04,X,BENGALURU,Kl rahul,Adult
4,Hardik Pandya,31,Ahmedabad,1600000.00,2024-06-05,Y,AHMEDABAD,Hardik pandya,Adult
5,Jasprit Bumrah,30,Madhya Pradesh,1700000.00,2024-06-06,X,MADHYA PRADESH,Jasprit bumrah,Adult
6,Ravindra Jadeja,31,Pune,1550000.00,2024-06-07,Z,PUNE,Ravindra jadeja,Adult
7,Shubman Gill,25,Kolkata,1400000.00,2024-06-08,Y,KOLKATA,Shubman gill,Adult
8,Rishabh Pant,27,Delhi,1450000.00,2024-06-09,X,DELHI,Rishabh pant,Adult
9,Suryakumar Yadav,33,Maharashtra,1650000.00,2024-06-10,Y,MUMBAI,Suryakumar yadav,Adult
10,Ravindra Jadeja,34,Pune,1550000.00,2024-06-07,Y,PUNE,Ravindra jadeja,Adult
11,Shubman Gill,25,Kolkata,1630769.23,2024-06-08,Y,KOLKATA,Shubman gill,Adult

In [579]:
data2 = pd.DataFrame({"A":[1,2,3],"B":[4,5,6]}) 
data2

   A  B
0  1  4
1  2  5
2  3  6

In [580]:
data2.applymap(lambda x: x **2)

   A   B
0  1  16
1  4  25
2  9  36

### **Data Aggregation**

In [581]:
df2.dtypes

Full Name        object
Age               int64
City             object
Salary          float64
Date             object
Category         object
City1            object
Name1            object
Age Category     object
dtype: object

In [582]:
sum_of_Salary = df2['Salary'].sum()
sum_of_Salary

np.float64(19730769.23)

In [583]:
min_Salary = df2['Salary'].min()
min_Salary

np.float64(1400000.0)

In [584]:
max_Salary = df['Salary'].max()
max_Salary

np.int64(6000)

In [585]:
avg_Age = round(df2['Age'].mean())
avg_Age

32

In [586]:
mid_Age = round(df2['Age'].median())
mid_Age

32

In [587]:
most_occured = df2['Category'].mode()
most_occured

0    Y
Name: Category, dtype: object

In [588]:
Standard_Age = df2['Age'].std()
Standard_Age

np.float64(4.84533515118126)

In [589]:
var_Age = df2['Age'].var()
var_Age

np.float64(23.477272727272727)

In [590]:
np.sqrt(var_Age) == Standard_Age

np.True_

In [591]:
df2['Category'][df2['Category'] == 'B'].count()

np.int64(0)

In [592]:
df2[df2['Category'] == 'B']['Category'].count()

np.int64(0)

In [593]:
df2['Age'].idxmax()

2

In [594]:
df2['Age'].idxmin()

7

In [595]:
df2['Age'].sort_values(ascending=True)

7     25
11    25
8     27
5     30
4     31
6     31
3     32
9     33
10    34
0     35
1     36
2     42
Name: Age, dtype: int64

In [596]:
df2['Age'].rank(ascending=True)

0     10.0
1     11.0
2     12.0
3      7.0
4      5.5
5      4.0
6      5.5
7      1.5
8      3.0
9      8.0
10     9.0
11     1.5
Name: Age, dtype: float64

In [597]:
df2[df2['Age'].between(35,60)]

,Full Name,Age,City,Salary,Date,Category,City1,Name1,Age Category
0,Virat Kohli,35,Maharashtra,1850000.0,2024-06-01,X,MUMBAI,Virat kohli,Middle Age
1,Rohit Sharma,36,Delhi,1750000.0,2024-06-02,Y,DELHI,Rohit sharma,Middle Age
2,Dhoni,42,Chennai,2100000.0,2024-06-03,Z,CHENNAI,Dhoni,Middle Age

In [598]:
df2

,Full Name,Age,City,Salary,Date,Category,City1,Name1,Age Category
0,Virat Kohli,35,Maharashtra,1850000.00,2024-06-01,X,MUMBAI,Virat kohli,Middle Age
1,Rohit Sharma,36,Delhi,1750000.00,2024-06-02,Y,DELHI,Rohit sharma,Middle Age
2,Dhoni,42,Chennai,2100000.00,2024-06-03,Z,CHENNAI,Dhoni,Middle Age
3,KL Rahul,32,Karnataka,1500000.00,2024-06-04,X,BENGALURU,Kl rahul,Adult
4,Hardik Pandya,31,Ahmedabad,1600000.00,2024-06-05,Y,AHMEDABAD,Hardik pandya,Adult
5,Jasprit Bumrah,30,Madhya Pradesh,1700000.00,2024-06-06,X,MADHYA PRADESH,Jasprit bumrah,Adult
6,Ravindra Jadeja,31,Pune,1550000.00,2024-06-07,Z,PUNE,Ravindra jadeja,Adult
7,Shubman Gill,25,Kolkata,1400000.00,2024-06-08,Y,KOLKATA,Shubman gill,Adult
8,Rishabh Pant,27,Delhi,1450000.00,2024-06-09,X,DELHI,Rishabh pant,Adult
9,Suryakumar Yadav,33,Maharashtra,1650000.00,2024-06-10,Y,MUMBAI,Suryakumar yadav,Adult
10,Ravindra Jadeja,34,Pune,1550000.00,2024-06-07,Y,PUNE,Ravindra jadeja,Adult
11,Shubman Gill,25,Kolkata,1630769.23,2024-06-08,Y,KOLKATA,Shubman gill,Adult

In [599]:
df2['Age'].add(1)

0     36
1     37
2     43
3     33
4     32
5     31
6     32
7     26
8     28
9     34
10    35
11    26
Name: Age, dtype: int64

In [600]:
df2['Age'].subtract(1)

0     34
1     35
2     41
3     31
4     30
5     29
6     30
7     24
8     26
9     32
10    33
11    24
Name: Age, dtype: int64

In [601]:
df2['Age'].multiply(2)

0     70
1     72
2     84
3     64
4     62
5     60
6     62
7     50
8     54
9     66
10    68
11    50
Name: Age, dtype: int64

In [602]:
df2['Age'].div(2)

0     17.5
1     18.0
2     21.0
3     16.0
4     15.5
5     15.0
6     15.5
7     12.5
8     13.5
9     16.5
10    17.0
11    12.5
Name: Age, dtype: float64

In [603]:
df2['Age'].mod(2)

0     1
1     0
2     0
3     0
4     1
5     0
6     1
7     1
8     1
9     1
10    0
11    1
Name: Age, dtype: int64

In [604]:
df2[df2['Age'].ge(35)]

,Full Name,Age,City,Salary,Date,Category,City1,Name1,Age Category
0,Virat Kohli,35,Maharashtra,1850000.0,2024-06-01,X,MUMBAI,Virat kohli,Middle Age
1,Rohit Sharma,36,Delhi,1750000.0,2024-06-02,Y,DELHI,Rohit sharma,Middle Age
2,Dhoni,42,Chennai,2100000.0,2024-06-03,Z,CHENNAI,Dhoni,Middle Age

In [605]:
df2['Category'].value_counts().index

Index(['Y', 'X', 'Z'], dtype='object', name='Category')

In [606]:
df2['Category'].value_counts().values

array([6, 4, 2])

In [607]:
df2

,Full Name,Age,City,Salary,Date,Category,City1,Name1,Age Category
0,Virat Kohli,35,Maharashtra,1850000.00,2024-06-01,X,MUMBAI,Virat kohli,Middle Age
1,Rohit Sharma,36,Delhi,1750000.00,2024-06-02,Y,DELHI,Rohit sharma,Middle Age
2,Dhoni,42,Chennai,2100000.00,2024-06-03,Z,CHENNAI,Dhoni,Middle Age
3,KL Rahul,32,Karnataka,1500000.00,2024-06-04,X,BENGALURU,Kl rahul,Adult
4,Hardik Pandya,31,Ahmedabad,1600000.00,2024-06-05,Y,AHMEDABAD,Hardik pandya,Adult
5,Jasprit Bumrah,30,Madhya Pradesh,1700000.00,2024-06-06,X,MADHYA PRADESH,Jasprit bumrah,Adult
6,Ravindra Jadeja,31,Pune,1550000.00,2024-06-07,Z,PUNE,Ravindra jadeja,Adult
7,Shubman Gill,25,Kolkata,1400000.00,2024-06-08,Y,KOLKATA,Shubman gill,Adult
8,Rishabh Pant,27,Delhi,1450000.00,2024-06-09,X,DELHI,Rishabh pant,Adult
9,Suryakumar Yadav,33,Maharashtra,1650000.00,2024-06-10,Y,MUMBAI,Suryakumar yadav,Adult
10,Ravindra Jadeja,34,Pune,1550000.00,2024-06-07,Y,PUNE,Ravindra jadeja,Adult
11,Shubman Gill,25,Kolkata,1630769.23,2024-06-08,Y,KOLKATA,Shubman gill,Adult

In [608]:
df2[df2['Category'] == "X"]

,Full Name,Age,City,Salary,Date,Category,City1,Name1,Age Category
0,Virat Kohli,35,Maharashtra,1850000.0,2024-06-01,X,MUMBAI,Virat kohli,Middle Age
3,KL Rahul,32,Karnataka,1500000.0,2024-06-04,X,BENGALURU,Kl rahul,Adult
5,Jasprit Bumrah,30,Madhya Pradesh,1700000.0,2024-06-06,X,MADHYA PRADESH,Jasprit bumrah,Adult
8,Rishabh Pant,27,Delhi,1450000.0,2024-06-09,X,DELHI,Rishabh pant,Adult

In [609]:
df2.groupby('Category')['Salary'].max()

Category
X    1850000.0
Y    1750000.0
Z    2100000.0
Name: Salary, dtype: float64

In [610]:
city_wise_salary = df2.groupby('City')['Salary'].sum()
city_wise_salary

City
Ahmedabad         1600000.00
Chennai           2100000.00
Delhi             3200000.00
Karnataka         1500000.00
Kolkata           3030769.23
Madhya Pradesh    1700000.00
Maharashtra       3500000.00
Pune              3100000.00
Name: Salary, dtype: float64

In [612]:
city_wise_salary.index

Index(['Ahmedabad', 'Chennai', 'Delhi', 'Karnataka', 'Kolkata',
       'Madhya Pradesh', 'Maharashtra', 'Pune'],
      dtype='object', name='City')

In [613]:
city_wise_salary.values

array([1600000.  , 2100000.  , 3200000.  , 1500000.  , 3030769.23,
       1700000.  , 3500000.  , 3100000.  ])

In [614]:
df2.groupby('City').agg({'Age':'mean'})

                 Age
City
Ahmedabad       31.0
Chennai         42.0
Delhi           31.5
Karnataka       32.0
Kolkata         25.0
Madhya Pradesh  30.0
Maharashtra     34.0
Pune            32.5

In [615]:
df2.groupby(['Category','Age Category']).agg({"Salary":"sum"}).sort_values(by='Salary', ascending=False).reset_index()

  Category Age Category      Salary
0        Y        Adult  7830769.23
1        X        Adult  4650000.00
2        Z   Middle Age  2100000.00
3        X   Middle Age  1850000.00
4        Y   Middle Age  1750000.00
5        Z        Adult  1550000.00

In [616]:
df2.groupby(['Category','Age Category']).agg({"Salary":"sum", "Age":'mean'}).reset_index()

  Category Age Category      Salary        Age
0        X        Adult  4650000.00  29.666667
1        X   Middle Age  1850000.00  35.000000
2        Y        Adult  7830769.23  29.600000
3        Y   Middle Age  1750000.00  36.000000
4        Z        Adult  1550000.00  31.000000
5        Z   Middle Age  2100000.00  42.000000

In [617]:
category_salary_age = df2.groupby('Age Category').agg({"Salary":["min", "max"], "Age":["min", "max"]})
category_salary_age

                 Salary            Age
                    min        max min max
Age Category
Adult         1400000.0  1700000.0  25  34
Middle Age    1750000.0  2100000.0  35  42

In [618]:
category_salary_age.unstack()

             Age Category
Salary  min  Adult           1400000.0
             Middle Age      1750000.0
        max  Adult           1700000.0
             Middle Age      2100000.0
Age     min  Adult                25.0
             Middle Age           35.0
        max  Adult                34.0
             Middle Age           42.0
dtype: float64

In [619]:
Numarical = df2.select_dtypes(include=['int', 'float']).columns.tolist()
Categorical = df2.select_dtypes(exclude=['int', 'float']).columns.tolist()
print("Numerical Columns: ", Numarical)
print("Categorical Columns: ", Categorical)

Numerical Columns:  ['Age', 'Salary']
Categorical Columns:  ['Full Name', 'City', 'Date', 'Category', 'City1', 'Name1', 'Age Category']