## **Pandas**

Pandas is open-source Python library which is used for data manipulation and analysis. It consist of data structures and functions to perform efficient operations on data. It is well-suited for working with tabular data such as spreadsheets or SQL tables. It is used in data science because it works well with other important libraries. It is built on top of the NumPy library as it makes easier to manipulate and analyze.

> Here's an overview of key aspects of the Pandas library:

1. Data Structures:

Series: A one-dimensional array capable of holding any data type. It's similar to a column in a spreadsheet or a single variable in statistics.

DataFrame: A two-dimensional table with rows and columns. It can be thought of as a spreadsheet or SQL table, where each column can be a different data type.

2. Data Loading and Saving:

Pandas provides functions to read data from various file formats such as CSV, Excel, SQL databases, JSON, and more.

It also allows you to write data back to these formats.

3. Data Cleaning and Preparation:

Pandas offers powerful tools for cleaning and preparing data, including handling missing values, filtering, sorting, and merging datasets.

Methods like dropna(), fillna(), and duplicated() are commonly used for data cleaning.

4. Indexing and Selecting Data:

Pandas uses labels for indexing and selecting data. The loc and iloc attributes are commonly used for label-based and integer-based indexing, respectively.

Conditional indexing is a powerful feature for selecting specific subsets of data.

5. Operations and Transformations:

Pandas supports element-wise operations between series and dataframes, similar to NumPy.

It provides various statistical and mathematical operations, along with methods like groupby for aggregating data.

6. Visualization:

While Pandas itself is not a visualization library, it integrates well with Matplotlib and Seaborn for creating visualizations.

DataFrames have built-in plotting methods for quick exploratory data visualization.

7. Integration with Other Libraries:

Pandas is often used in conjunction with other libraries like NumPy, Matplotlib, and Scikit-Learn to form a powerful data analysis and machine learning toolkit.

8. Use Cases:

Pandas is widely used for data cleaning, exploration, and analysis in fields such as finance, economics, social sciences, and more.

It is a foundational tool for data scientists, analysts, and researchers working with structured data.

Pandas is a versatile library that plays a crucial role in the Python ecosystem for data analysis. Its flexibility and ease of use make it a popular choice for handling and analyzing tabular data.

[Pandas](https://pandas.pydata.org/docs/)

In [243]:
#pip install pandas

In [244]:
#pip show pandas

In [245]:
import pandas
import pandas as pd
from pandas import pandas as pd

In [246]:
import warnings
warnings.filterwarnings('ignore')

In [247]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [248]:
pd.__version__

'2.2.3'

In [249]:
print(pd.__doc__)

pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

### **Series**

A Series is a one-dimensional array-like object in Pandas.

It is similar to a column in a spreadsheet or a single variable in statistics.

Each element in a series has an associated index, which can be explicitly set or is automatically generated.

You can create a Series from a Python list, NumPy array, or dictionary.

A Pandas Series is a one-dimensional array of indexed data.

#### Syntax : pd.Series(data, index=index)

In [251]:
age = [20,25,23,30,41,12,10,15,60]
index = ['a','b','c','d','e','f','g','h','i']

series = pd.Series(data=age, index=index, name='Series')
series

a    20
b    25
c    23
d    30
e    41
f    12
g    10
h    15
i    60
Name: Series, dtype: int64

### **DataFrame**

A DataFrame is a two-dimensional table with rows and columns, similar to a spreadsheet or a SQL table.

It is the primary data structure in Pandas and is used for most data manipulation and analysis tasks.

Each column in a DataFrame is a Series.

DataFrame allows you to handle heterogeneous data types and supports a wide range of operations.

An effective object/data structure offered by PANDAS that allows us to handle the tabular form of data(which is basically what we get to work with on a day to day basis)

#### Syntax : pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)

In [252]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ivan', 'Jack', 'Ivan', 'Jack', 'Grace', 'Hannah'],  
    'Age': [45, 58, 60, 28, 49, 67, None, 60, 37, 31, 37, 31, 29, 60],  
    'City': ['New York', 'London', 'Tokyo', 'Paris', 'Berlin', 'Paris', 'Berlin', 'New York', 'Tokyo', 'London', 'Tokyo', 'London', 'Berlin', 'New York'],  
    'Salary': [95445, 86235, 62330, 46022, 65999, 88320, 57141, 65413, 87016, 58725, 87016, 58725, 57141, None],  
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10', '2023-01-09', '2023-01-10', '2023-01-07', '2023-01-08'],  
    'Category': ['A', 'B', 'C', 'A', 'B', 'A', 'C', 'B', 'A', 'B', 'A', 'B', None, 'B']  
}

In [253]:
print(pd.DataFrame.__doc__)

Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

    .. versionchanged:: 1.3.0

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
...                    columns=['a', 'b', 'c'])
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
>>> df3 = pd.DataFrame(data, columns=['c', 'a'])
...
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3

In [254]:
df = pd.DataFrame(data=data)
df

       Name   Age      City   Salary        Date Category
0     Alice  45.0  New York  95445.0  2023-01-01        A
1       Bob  58.0    London  86235.0  2023-01-02        B
2   Charlie  60.0     Tokyo  62330.0  2023-01-03        C
3     David  28.0     Paris  46022.0  2023-01-04        A
4       Eva  49.0    Berlin  65999.0  2023-01-05        B
5     Frank  67.0     Paris  88320.0  2023-01-06        A
6     Grace   NaN    Berlin  57141.0  2023-01-07        C
7    Hannah  60.0  New York  65413.0  2023-01-08        B
8      Ivan  37.0     Tokyo  87016.0  2023-01-09        A
9      Jack  31.0    London  58725.0  2023-01-10        B
10     Ivan  37.0     Tokyo  87016.0  2023-01-09        A
11     Jack  31.0    London  58725.0  2023-01-10        B
12    Grace  29.0    Berlin  57141.0  2023-01-07     None
13   Hannah  60.0  New York      NaN  2023-01-08        B

### **Data Ingestion**

In [255]:
df1 = pd.read_csv(r'data.csv')
df1

       Name   Age      City   Salary        Date Category
0     Alice  45.0  New York  95445.0  2023-01-01        A
1       Bob  58.0    London  86235.0  2023-01-02        B
2   Charlie  60.0     Tokyo  62330.0  2023-01-03        C
3     David  28.0     Paris  46022.0  2023-01-04        A
4       Eva  49.0    Berlin  65999.0  2023-01-05        B
5     Frank  67.0     Paris  88320.0  2023-01-06        A
6     Grace   NaN    Berlin  57141.0  2023-01-07        C
7    Hannah  60.0  New York  65413.0  2023-01-08        B
8      Ivan  37.0     Tokyo  87016.0  2023-01-09        A
9      Jack  31.0    London  58725.0  2023-01-10        B
10     Ivan  37.0     Tokyo  87016.0  2023-01-09        A
11     Jack  31.0    London  58725.0  2023-01-10        B
12    Grace  29.0    Berlin  57141.0  2023-01-07      NaN
13   Hannah  60.0  New York      NaN  2023-01-08        B

In [256]:
# pip install openpyxl for excel file reader
df2 = pd.read_excel(r'data.xlsx', sheet_name='Data')
df2

       Name   Age      City   Salary        Date Category
0     Alice  45.0  New York  95445.0  2023-01-01        A
1       Bob  58.0    London  86235.0  2023-01-02        B
2   Charlie  60.0     Tokyo  62330.0  2023-01-03        C
3     David  28.0     Paris  46022.0  2023-01-04        A
4       Eva  49.0    Berlin  65999.0  2023-01-05        B
5     Frank  67.0     Paris  88320.0  2023-01-06        A
6     Grace   NaN    Berlin  57141.0  2023-01-07        C
7    Hannah  60.0  New York  65413.0  2023-01-08        B
8      Ivan  37.0     Tokyo  87016.0  2023-01-09        A
9      Jack  31.0    London  58725.0  2023-01-10        B
10     Ivan  37.0     Tokyo  87016.0  2023-01-09        A
11     Jack  31.0    London  58725.0  2023-01-10        B
12    Grace  29.0    Berlin  57141.0  2023-01-07      NaN
13   Hannah  60.0  New York      NaN  2023-01-08        B

In [257]:
# pd.read_json('data.json')
# pd.read_sql(query, mydb)

### **Data Store**

```
df.to_csv(r"C:\Users\Admin\Downloads\data.csv", index=False)
df.to_excel(r"C:\Users\Admin\Downloads\data.xlsx", index=False, sheet_name='Data')
df.to_json(r"C:\Users\Admin\Downloads\data.json", index=False, orient='records', indent=4)
df.to_sql('my_table', engine, index=False, if_exists='replace')
```

### **Data Extraction**

```
# Set pandas to display all rows
pd.set_option('display.max_rows', None)

# Set pandas to display all columns
pd.set_option('display.max_columns', None)
```

In [258]:
df.head(2) # Defalut top 5 rows

    Name   Age      City   Salary        Date Category
0  Alice  45.0  New York  95445.0  2023-01-01        A
1    Bob  58.0    London  86235.0  2023-01-02        B

In [259]:
df.tail() # Defalut bottom 5 rows

      Name   Age      City   Salary        Date Category
9     Jack  31.0    London  58725.0  2023-01-10        B
10    Ivan  37.0     Tokyo  87016.0  2023-01-09        A
11    Jack  31.0    London  58725.0  2023-01-10        B
12   Grace  29.0    Berlin  57141.0  2023-01-07     None
13  Hannah  60.0  New York      NaN  2023-01-08        B

In [260]:
df.shape # Dimensionality of the data

(14, 6)

In [261]:
df.shape[0] # rows

14

In [262]:
df.shape[1] # columns

6

In [263]:
df.size # size of datase

84

In [264]:
df.dtypes # data type of each column

Name         object
Age         float64
City         object
Salary      float64
Date         object
Category     object
dtype: object

In [265]:
df.Name.dtype

dtype('O')

In [266]:
df.columns # Accessing All columns

Index(['Name', 'Age', 'City', 'Salary', 'Date', 'Category'], dtype='object')

In [267]:
df.columns[:5]

Index(['Name', 'Age', 'City', 'Salary', 'Date'], dtype='object')

In [268]:
df.info() # entire information about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      14 non-null     object
 1   Age       13 non-null     float64
 2   City      14 non-null     object
 3   Salary    13 non-null     float64
 4   Date      14 non-null     object
 5   Category  13 non-null     object
dtypes: float64(2), object(4)
memory usage: 804.0+ bytes

In [269]:
for col in df.columns:
    print(f"{col} : {df[col].unique()}")

Name : ['Alice' 'Bob' 'Charlie' 'David' 'Eva' 'Frank' 'Grace' 'Hannah' 'Ivan'
 'Jack']
Age : [45. 58. 60. 28. 49. 67. nan 37. 31. 29.]
City : ['New York' 'London' 'Tokyo' 'Paris' 'Berlin']
Salary : [95445. 86235. 62330. 46022. 65999. 88320. 57141. 65413. 87016. 58725.
    nan]
Date : ['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09' '2023-01-10']
Category : ['A' 'B' 'C' None]

In [270]:
df.nunique() # Sum of Unique Values

Name        10
Age          9
City         5
Salary      10
Date        10
Category     3
dtype: int64

In [271]:
df.Age.nsmallest(2) # Make Ascending order

3     28.0
12    29.0
Name: Age, dtype: float64

In [272]:
df.Age.nlargest() # Make Disecnding Order

5     67.0
2     60.0
7     60.0
13    60.0
1     58.0
Name: Age, dtype: float64

In [273]:
df.describe().T # Statistical Description of Numarical Data

,count,mean,std,min,25%,50%,75%,max
Age,13.0,45.538462,14.157539,28.0,31.0,45.0,60.0,67.0
Salary,13.0,70425.230769,16018.646562,46022.0,58725.0,65413.0,87016.0,95445.0

In [274]:
df.describe(include='object').T

         count unique         top freq
Name        14     10        Ivan    2
City        14      5    New York    3
Date        14     10  2023-01-09    2
Category    13      3           B    6

### **Data Manipulation**
### **Indexing, Accessing, and Slicing**

In [275]:
df.Name # or df['Name']

0       Alice
1         Bob
2     Charlie
3       David
4         Eva
5       Frank
6       Grace
7      Hannah
8        Ivan
9        Jack
10       Ivan
11       Jack
12      Grace
13     Hannah
Name: Name, dtype: object

In [276]:
df[['Name']]

       Name
0     Alice
1       Bob
2   Charlie
3     David
4       Eva
5     Frank
6     Grace
7    Hannah
8      Ivan
9      Jack
10     Ivan
11     Jack
12    Grace
13   Hannah

In [277]:
df[['Name', 'Age']]

       Name   Age
0     Alice  45.0
1       Bob  58.0
2   Charlie  60.0
3     David  28.0
4       Eva  49.0
5     Frank  67.0
6     Grace   NaN
7    Hannah  60.0
8      Ivan  37.0
9      Jack  31.0
10     Ivan  37.0
11     Jack  31.0
12    Grace  29.0
13   Hannah  60.0

In [278]:
col = df.columns[:4]
df[col]

       Name   Age      City   Salary
0     Alice  45.0  New York  95445.0
1       Bob  58.0    London  86235.0
2   Charlie  60.0     Tokyo  62330.0
3     David  28.0     Paris  46022.0
4       Eva  49.0    Berlin  65999.0
5     Frank  67.0     Paris  88320.0
6     Grace   NaN    Berlin  57141.0
7    Hannah  60.0  New York  65413.0
8      Ivan  37.0     Tokyo  87016.0
9      Jack  31.0    London  58725.0
10     Ivan  37.0     Tokyo  87016.0
11     Jack  31.0    London  58725.0
12    Grace  29.0    Berlin  57141.0
13   Hannah  60.0  New York      NaN

#### **Slicing**

In [279]:
df[1:10]

      Name   Age      City   Salary        Date Category
1      Bob  58.0    London  86235.0  2023-01-02        B
2  Charlie  60.0     Tokyo  62330.0  2023-01-03        C
3    David  28.0     Paris  46022.0  2023-01-04        A
4      Eva  49.0    Berlin  65999.0  2023-01-05        B
5    Frank  67.0     Paris  88320.0  2023-01-06        A
6    Grace   NaN    Berlin  57141.0  2023-01-07        C
7   Hannah  60.0  New York  65413.0  2023-01-08        B
8     Ivan  37.0     Tokyo  87016.0  2023-01-09        A
9     Jack  31.0    London  58725.0  2023-01-10        B

In [280]:
df[1:10:2]

     Name   Age      City   Salary        Date Category
1     Bob  58.0    London  86235.0  2023-01-02        B
3   David  28.0     Paris  46022.0  2023-01-04        A
5   Frank  67.0     Paris  88320.0  2023-01-06        A
7  Hannah  60.0  New York  65413.0  2023-01-08        B
9    Jack  31.0    London  58725.0  2023-01-10        B

#### **Categorical Accesing**
- there is no excluse

In [281]:
df.loc[1] # accessing 1 row

Name               Bob
Age               58.0
City            London
Salary         86235.0
Date        2023-01-02
Category             B
Name: 1, dtype: object

In [282]:
df.loc[:10:2]

       Name   Age      City   Salary        Date Category
0     Alice  45.0  New York  95445.0  2023-01-01        A
2   Charlie  60.0     Tokyo  62330.0  2023-01-03        C
4       Eva  49.0    Berlin  65999.0  2023-01-05        B
6     Grace   NaN    Berlin  57141.0  2023-01-07        C
8      Ivan  37.0     Tokyo  87016.0  2023-01-09        A
10     Ivan  37.0     Tokyo  87016.0  2023-01-09        A

In [283]:
df.loc[:10 , "Name":"Salary":2]

       Name      City
0     Alice  New York
1       Bob    London
2   Charlie     Tokyo
3     David     Paris
4       Eva    Berlin
5     Frank     Paris
6     Grace    Berlin
7    Hannah  New York
8      Ivan     Tokyo
9      Jack    London
10     Ivan     Tokyo

#### **Numarical Accessing**

In [284]:
df.iloc[:12]

       Name   Age      City   Salary        Date Category
0     Alice  45.0  New York  95445.0  2023-01-01        A
1       Bob  58.0    London  86235.0  2023-01-02        B
2   Charlie  60.0     Tokyo  62330.0  2023-01-03        C
3     David  28.0     Paris  46022.0  2023-01-04        A
4       Eva  49.0    Berlin  65999.0  2023-01-05        B
5     Frank  67.0     Paris  88320.0  2023-01-06        A
6     Grace   NaN    Berlin  57141.0  2023-01-07        C
7    Hannah  60.0  New York  65413.0  2023-01-08        B
8      Ivan  37.0     Tokyo  87016.0  2023-01-09        A
9      Jack  31.0    London  58725.0  2023-01-10        B
10     Ivan  37.0     Tokyo  87016.0  2023-01-09        A
11     Jack  31.0    London  58725.0  2023-01-10        B

In [285]:
df.iloc[:12, 0:5:2]

       Name      City        Date
0     Alice  New York  2023-01-01
1       Bob    London  2023-01-02
2   Charlie     Tokyo  2023-01-03
3     David     Paris  2023-01-04
4       Eva    Berlin  2023-01-05
5     Frank     Paris  2023-01-06
6     Grace    Berlin  2023-01-07
7    Hannah  New York  2023-01-08
8      Ivan     Tokyo  2023-01-09
9      Jack    London  2023-01-10
10     Ivan     Tokyo  2023-01-09
11     Jack    London  2023-01-10

#### **Boolean Indexing**

In [286]:
df.head()

      Name   Age      City   Salary        Date Category
0    Alice  45.0  New York  95445.0  2023-01-01        A
1      Bob  58.0    London  86235.0  2023-01-02        B
2  Charlie  60.0     Tokyo  62330.0  2023-01-03        C
3    David  28.0     Paris  46022.0  2023-01-04        A
4      Eva  49.0    Berlin  65999.0  2023-01-05        B

In [287]:
df['Age'] > 30

0      True
1      True
2      True
3     False
4      True
5      True
6     False
7      True
8      True
9      True
10     True
11     True
12    False
13     True
Name: Age, dtype: bool

In [288]:
df[df['Age'] > 30]

       Name   Age      City   Salary        Date Category
0     Alice  45.0  New York  95445.0  2023-01-01        A
1       Bob  58.0    London  86235.0  2023-01-02        B
2   Charlie  60.0     Tokyo  62330.0  2023-01-03        C
4       Eva  49.0    Berlin  65999.0  2023-01-05        B
5     Frank  67.0     Paris  88320.0  2023-01-06        A
7    Hannah  60.0  New York  65413.0  2023-01-08        B
8      Ivan  37.0     Tokyo  87016.0  2023-01-09        A
9      Jack  31.0    London  58725.0  2023-01-10        B
10     Ivan  37.0     Tokyo  87016.0  2023-01-09        A
11     Jack  31.0    London  58725.0  2023-01-10        B
13   Hannah  60.0  New York      NaN  2023-01-08        B

In [289]:
df[df['Category'] == 'C']

      Name   Age    City   Salary        Date Category
2  Charlie  60.0   Tokyo  62330.0  2023-01-03        C
6    Grace   NaN  Berlin  57141.0  2023-01-07        C

In [290]:
df[(df['Age'] > 30) & (df['Category'] == 'A')]

     Name   Age      City   Salary        Date Category
0   Alice  45.0  New York  95445.0  2023-01-01        A
5   Frank  67.0     Paris  88320.0  2023-01-06        A
8    Ivan  37.0     Tokyo  87016.0  2023-01-09        A
10   Ivan  37.0     Tokyo  87016.0  2023-01-09        A

In [291]:
df[(df['Age'] > 30) | (df['City'] == 'Tokyo')]

       Name   Age      City   Salary        Date Category
0     Alice  45.0  New York  95445.0  2023-01-01        A
1       Bob  58.0    London  86235.0  2023-01-02        B
2   Charlie  60.0     Tokyo  62330.0  2023-01-03        C
4       Eva  49.0    Berlin  65999.0  2023-01-05        B
5     Frank  67.0     Paris  88320.0  2023-01-06        A
7    Hannah  60.0  New York  65413.0  2023-01-08        B
8      Ivan  37.0     Tokyo  87016.0  2023-01-09        A
9      Jack  31.0    London  58725.0  2023-01-10        B
10     Ivan  37.0     Tokyo  87016.0  2023-01-09        A
11     Jack  31.0    London  58725.0  2023-01-10        B
13   Hannah  60.0  New York      NaN  2023-01-08        B

#### **isin**

In [292]:
df[df['Category'].isin(['A','B'])]

      Name   Age      City   Salary        Date Category
0    Alice  45.0  New York  95445.0  2023-01-01        A
1      Bob  58.0    London  86235.0  2023-01-02        B
3    David  28.0     Paris  46022.0  2023-01-04        A
4      Eva  49.0    Berlin  65999.0  2023-01-05        B
5    Frank  67.0     Paris  88320.0  2023-01-06        A
7   Hannah  60.0  New York  65413.0  2023-01-08        B
8     Ivan  37.0     Tokyo  87016.0  2023-01-09        A
9     Jack  31.0    London  58725.0  2023-01-10        B
10    Ivan  37.0     Tokyo  87016.0  2023-01-09        A
11    Jack  31.0    London  58725.0  2023-01-10        B
13  Hannah  60.0  New York      NaN  2023-01-08        B

In [293]:
df[df['City'].isin(['New York', 'San Fransisco', 'London'])]

      Name   Age      City   Salary        Date Category
0    Alice  45.0  New York  95445.0  2023-01-01        A
1      Bob  58.0    London  86235.0  2023-01-02        B
7   Hannah  60.0  New York  65413.0  2023-01-08        B
9     Jack  31.0    London  58725.0  2023-01-10        B
11    Jack  31.0    London  58725.0  2023-01-10        B
13  Hannah  60.0  New York      NaN  2023-01-08        B

#### **Query**

In [294]:
df.query('Age > 30')

       Name   Age      City   Salary        Date Category
0     Alice  45.0  New York  95445.0  2023-01-01        A
1       Bob  58.0    London  86235.0  2023-01-02        B
2   Charlie  60.0     Tokyo  62330.0  2023-01-03        C
4       Eva  49.0    Berlin  65999.0  2023-01-05        B
5     Frank  67.0     Paris  88320.0  2023-01-06        A
7    Hannah  60.0  New York  65413.0  2023-01-08        B
8      Ivan  37.0     Tokyo  87016.0  2023-01-09        A
9      Jack  31.0    London  58725.0  2023-01-10        B
10     Ivan  37.0     Tokyo  87016.0  2023-01-09        A
11     Jack  31.0    London  58725.0  2023-01-10        B
13   Hannah  60.0  New York      NaN  2023-01-08        B

In [295]:
df.query('Category == "C"')

      Name   Age    City   Salary        Date Category
2  Charlie  60.0   Tokyo  62330.0  2023-01-03        C
6    Grace   NaN  Berlin  57141.0  2023-01-07        C

In [296]:
df.query('Age > 30 and Category == "C"')

      Name   Age   City   Salary        Date Category
2  Charlie  60.0  Tokyo  62330.0  2023-01-03        C

#### **Where**

In [297]:
import numpy as np

In [298]:
np.where(df['Age'] > 30) # Based on the index Validate

(array([ 0,  1,  2,  4,  5,  7,  8,  9, 10, 11, 13]),)

### **Accessing Value** and **Modifing**

In [299]:
df['Name'][2]

'Charlie'

In [300]:
print(f"Befor Modifieng : {df['Name'][2]}")

df['Name'][2] = 'Ash'

print(f"After Modifieng : {df['Name'][2]}")

Befor Modifieng : Charlie
After Modifieng : Ash

In [301]:
df.loc[2]

Name               Ash
Age               60.0
City             Tokyo
Salary         62330.0
Date        2023-01-03
Category             C
Name: 2, dtype: object

#### **String method**

In [302]:
df[df['City'].str.contains('london', case=False)] # Filtering the record based on the string value

    Name   Age    City   Salary        Date Category
1    Bob  58.0  London  86235.0  2023-01-02        B
9   Jack  31.0  London  58725.0  2023-01-10        B
11  Jack  31.0  London  58725.0  2023-01-10        B

In [303]:
df[df['City'].str.contains('London', case=False)]

    Name   Age    City   Salary        Date Category
1    Bob  58.0  London  86235.0  2023-01-02        B
9   Jack  31.0  London  58725.0  2023-01-10        B
11  Jack  31.0  London  58725.0  2023-01-10        B

In [304]:
df['City'].str.split(' ')

0     [New, York]
1        [London]
2         [Tokyo]
3         [Paris]
4        [Berlin]
5         [Paris]
6        [Berlin]
7     [New, York]
8         [Tokyo]
9        [London]
10        [Tokyo]
11       [London]
12       [Berlin]
13    [New, York]
Name: City, dtype: object

In [305]:
df['City'].str.split(' ').str.get(0)

0        New
1     London
2      Tokyo
3      Paris
4     Berlin
5      Paris
6     Berlin
7        New
8      Tokyo
9     London
10     Tokyo
11    London
12    Berlin
13       New
Name: City, dtype: object

In [306]:
df[df['Name'].str.startswith('A')]

    Name   Age      City   Salary        Date Category
0  Alice  45.0  New York  95445.0  2023-01-01        A
2    Ash  60.0     Tokyo  62330.0  2023-01-03        C

In [307]:
df[df['Name'].str.endswith('h')]

      Name   Age      City   Salary        Date Category
2      Ash  60.0     Tokyo  62330.0  2023-01-03        C
7   Hannah  60.0  New York  65413.0  2023-01-08        B
13  Hannah  60.0  New York      NaN  2023-01-08        B

In [308]:
df['Name1'] = df['Name'].str.upper()

In [309]:
df['Name1'] = df['Name'].str.lower()

In [310]:
df['Name1'] = df['Name'].str.capitalize()

In [311]:
df['Name'].str.count('Hannah').sum() # counting the occurence

np.int64(2)

In [312]:
df['Name'].add(' Mr')

0      Alice Mr
1        Bob Mr
2        Ash Mr
3      David Mr
4        Eva Mr
5      Frank Mr
6      Grace Mr
7     Hannah Mr
8       Ivan Mr
9       Jack Mr
10      Ivan Mr
11      Jack Mr
12     Grace Mr
13    Hannah Mr
Name: Name, dtype: object

In [313]:
df['City'] = df['City'].str.replace('London','India')

### **Data Cleaning**

In [314]:
data = pd.DataFrame({'A': [1, 2, None, 4, None, 6, 7, 1, 100], 'B': [7, None, 9, None, 11, None,50, 7, 7]})
data

       A     B
0    1.0   7.0
1    2.0   NaN
2    NaN   9.0
3    4.0   NaN
4    NaN  11.0
5    6.0   NaN
6    7.0  50.0
7    1.0   7.0
8  100.0   7.0

In [315]:
data.isnull().sum() # finding Missing Values

A    2
B    3
dtype: int64

In [316]:
data.isna().sum()

A    2
B    3
dtype: int64

In [317]:
data.notnull().sum()

A    7
B    6
dtype: int64

In [318]:
data.notna().sum()

A    7
B    6
dtype: int64

In [319]:
data.duplicated().sum() # finding Duplicates

np.int64(1)

In [320]:
# Finding Outlier
def find_outlier(df, columns):
    outlier_indices = set()
    
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lf = Q1 - 1.5 * IQR
        uf = Q3 + 1.5 * IQR
        col_outliers = df[(df[col] < lf) | (df[col] > uf)]
        outlier_indices.update(col_outliers.index)
        
    return df.loc[list(outlier_indices)]

outliers = find_outlier(data, ['A', 'B'])
print(outliers)

       A     B
8  100.0   7.0
6    7.0  50.0

#### **Handling Missing Values**

In [321]:
# data.dropna(subset=['B']) # Drop the missing values in a specific column
dropna = data.dropna()
dropna

       A     B
0    1.0   7.0
6    7.0  50.0
7    1.0   7.0
8  100.0   7.0

In [322]:
round(data['A'].mean(), 2)

np.float64(17.29)

In [323]:
data['A'].fillna(round(data['A'].mean(), 2)) # , inplace=True is to change in the raw data

0      1.00
1      2.00
2     17.29
3      4.00
4     17.29
5      6.00
6      7.00
7      1.00
8    100.00
Name: A, dtype: float64

In [324]:
data['B'].fillna(round(data['B'].mean(), 2))

0     7.00
1    15.17
2     9.00
3    15.17
4    11.00
5    15.17
6    50.00
7     7.00
8     7.00
Name: B, dtype: float64

In [ ]:
# data['A'].fillna(method='ffill') # forward fill
# data['B'].fillna(method='bfill') # bacword fill

In [325]:
data['A']

0      1.0
1      2.0
2      NaN
3      4.0
4      NaN
5      6.0
6      7.0
7      1.0
8    100.0
Name: A, dtype: float64

In [326]:
data['A'].interpolate() # replacce the null values avg of the srrounding values

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      1.0
8    100.0
Name: A, dtype: float64

In [327]:
data

       A     B
0    1.0   7.0
1    2.0   NaN
2    NaN   9.0
3    4.0   NaN
4    NaN  11.0
5    6.0   NaN
6    7.0  50.0
7    1.0   7.0
8  100.0   7.0

#### **Handling Duplicate**

In [328]:
data[data.duplicated()]

     A    B
7  1.0  7.0

In [329]:
data.drop_duplicates().reset_index(drop=True) # Rearrange the index (reset_index())

       A     B
0    1.0   7.0
1    2.0   NaN
2    NaN   9.0
3    4.0   NaN
4    NaN  11.0
5    6.0   NaN
6    7.0  50.0
7  100.0   7.0

#### **Handle the Outlier**

In [330]:
data.dropna(inplace=True)

In [331]:
data

       A     B
0    1.0   7.0
6    7.0  50.0
7    1.0   7.0
8  100.0   7.0

In [332]:
# Finding Outlier
def remove_outlier(df, columns):

    Cleaned_df = df.copy()
    
    for col in columns:
        Q1 = Cleaned_df[col].quantile(0.25)
        Q3 = Cleaned_df[col].quantile(0.75)
        IQR = Q3 - Q1
        lf = Q1 - 1.5 * IQR
        uf = Q3 + 1.5 * IQR
        
        Cleaned_df = Cleaned_df[(Cleaned_df[col] >= lf) & (Cleaned_df[col] <= uf)]
        
    return Cleaned_df

outliers = remove_outlier(data, ['A', 'B'])
print(outliers)

     A     B
0  1.0   7.0
6  7.0  50.0
7  1.0   7.0

In [333]:
Q1 = data['B'].quantile(0.25)
Q1

np.float64(7.0)

In [334]:
Q3 = data['B'].quantile(0.75)
Q3

np.float64(17.75)

In [335]:
IQR = Q3-Q1
lf = Q1 - 1.5 * IQR
lf

np.float64(-9.125)

In [336]:
uf = Q3 + 1.5 * IQR
uf

np.float64(33.875)

In [337]:
def log_transformation(df, columns):
    
    tranform_df = df.copy()

    for col in columns:
        tranform_df[col] = np.log1p(tranform_df[col]) # log1p = lg(1+x)
    return tranform_df

log = log_transformation(data, ['A', 'B'])
log

          A         B
0  0.693147  2.079442
6  2.079442  3.931826
7  0.693147  2.079442
8  4.615121  2.079442

In [338]:
data

       A     B
0    1.0   7.0
6    7.0  50.0
7    1.0   7.0
8  100.0   7.0

In [339]:
df.isnull().sum()

Name        0
Age         1
City        0
Salary      1
Date        0
Category    1
Name1       0
dtype: int64

In [340]:
df.duplicated().sum()

np.int64(2)

In [341]:
df['Age'].fillna(round(df['Age'].mean(), 2), inplace=True)
df['Salary'].fillna(round(df['Salary'].mean(), 2), inplace=True)
df['Category'].fillna(df['Category'].mode()[0], inplace = True)

In [342]:
df.drop_duplicates(inplace=True)

In [343]:
df = df.reset_index(drop=True)

### **Data Transformation**

In [344]:
df.rename(columns={'Name':"Full Name"}, inplace =True)

In [345]:
df['Age'] = df['Age'].astype('int')

In [346]:
df['City'].replace({"New York":"London"}, inplace=True)

In [347]:
def Catgorize(col):
    if col < 18:
        return "Young"
    elif col < 35:
        return "Adult"
    elif col < 55:
        return "Middle Age"
    else:
        return "Senior"

In [348]:
df['Age Category'] = df['Age'].apply(Catgorize)

In [349]:
df

   Full Name  Age    City    Salary        Date Category   Name1 Age Category
0      Alice   45  London  95445.00  2023-01-01        A   Alice   Middle Age
1        Bob   58   India  86235.00  2023-01-02        B     Bob       Senior
2        Ash   60   Tokyo  62330.00  2023-01-03        C     Ash       Senior
3      David   28   Paris  46022.00  2023-01-04        A   David        Adult
4        Eva   49  Berlin  65999.00  2023-01-05        B     Eva   Middle Age
5      Frank   67   Paris  88320.00  2023-01-06        A   Frank       Senior
6      Grace   45  Berlin  57141.00  2023-01-07        C   Grace   Middle Age
7     Hannah   60  London  65413.00  2023-01-08        B  Hannah       Senior
8       Ivan   37   Tokyo  87016.00  2023-01-09        A    Ivan   Middle Age
9       Jack   31   India  58725.00  2023-01-10        B    Jack        Adult
10     Grace   29  Berlin  57141.00  2023-01-07        B   Grace        Adult
11    Hannah   60  London  70425.23  2023-01-08        B  Hannah       Senior

In [350]:
data1 = pd.DataFrame({"A":[1,2,3],"B":[4,5,6]}) 
data1

   A  B
0  1  4
1  2  5
2  3  6

In [351]:
data1.applymap(lambda x: x **2) # Element-wisw Function

   A   B
0  1  16
1  4  25
2  9  36

In [352]:
df.loc[12] = {"Full Name" : "Deepak", "Age":25, "City":"Bengalore", "Salary":60000, "Date":"2025-07-30", "Category":"A", "Name1":"DEEPAK", "Age Category":"Adult"}

In [353]:
df.loc[13] = ["Rohan", 25, "Bengalore", 60000, "2025-07-30", "A", "ROHAN", "Adult"] # match the all column values

In [354]:
df.drop(columns=['Name1'], inplace=True) # removing the columns

In [355]:
df.drop(13, inplace=True)

In [356]:
### **Data Aggregation**

In [357]:
df.dtypes

Full Name        object
Age               int64
City             object
Salary          float64
Date             object
Category         object
Age Category     object
dtype: object

In [358]:
sum_of_Salary = df['Salary'].sum()
sum_of_Salary

np.float64(900212.23)

In [359]:
min_Salary = df['Salary'].min()
min_Salary

np.float64(46022.0)

In [360]:
max_Salary = df['Salary'].max()
max_Salary

np.float64(95445.0)

In [361]:
avg_Age = round(df['Age'].mean())
avg_Age

46

In [362]:
middle_Age = round(df['Age'].median())
middle_Age

45

In [363]:
most_occured_category = df['Category'].mode()
most_occured_category

0    B
Name: Category, dtype: object

In [364]:
Std_Age = df['Age'].std()
Std_Age

np.float64(14.556697286728054)

In [365]:
var_Age = df['Age'].var()
var_Age

np.float64(211.89743589743588)

In [366]:
np.sqrt(var_Age) == Std_Age

np.True_

In [367]:
df['Category'][df['Category'] == 'B'].count()

np.int64(6)

In [368]:
df[df['Category'] == 'B']['Category'].count()

np.int64(6)

In [369]:
df['Age'].idxmax()

np.int64(5)

In [370]:
df['Age'].idxmin()

np.int64(12)

In [371]:
df['Age'].sort_values(ascending=True) # Sorting the elements

12    25
3     28
10    29
9     31
8     37
0     45
6     45
4     49
1     58
11    60
2     60
7     60
5     67
Name: Age, dtype: int64

In [372]:
df['Age'].rank(ascending=True)

0      6.5
1      9.0
2     11.0
3      2.0
4      8.0
5     13.0
6      6.5
7     11.0
8      5.0
9      4.0
10     3.0
11    11.0
12     1.0
Name: Age, dtype: float64

In [373]:
df[df['Age'].between(35,60)]

   Full Name  Age    City    Salary        Date Category Age Category
0      Alice   45  London  95445.00  2023-01-01        A   Middle Age
1        Bob   58   India  86235.00  2023-01-02        B       Senior
2        Ash   60   Tokyo  62330.00  2023-01-03        C       Senior
4        Eva   49  Berlin  65999.00  2023-01-05        B   Middle Age
6      Grace   45  Berlin  57141.00  2023-01-07        C   Middle Age
7     Hannah   60  London  65413.00  2023-01-08        B       Senior
8       Ivan   37   Tokyo  87016.00  2023-01-09        A   Middle Age
11    Hannah   60  London  70425.23  2023-01-08        B       Senior

In [374]:
df['Category'] = df['Category'].map({'A':'X', 'B':'Y', 'C':'Z'})

In [375]:
df['Age'].add(1)

0     46
1     59
2     61
3     29
4     50
5     68
6     46
7     61
8     38
9     32
10    30
11    61
12    26
Name: Age, dtype: int64

In [376]:
df['Age'].subtract(1)

0     44
1     57
2     59
3     27
4     48
5     66
6     44
7     59
8     36
9     30
10    28
11    59
12    24
Name: Age, dtype: int64

In [377]:
df['Age'].multiply(2)

0      90
1     116
2     120
3      56
4      98
5     134
6      90
7     120
8      74
9      62
10     58
11    120
12     50
Name: Age, dtype: int64

In [378]:
df['Age'].div(2)

0     22.5
1     29.0
2     30.0
3     14.0
4     24.5
5     33.5
6     22.5
7     30.0
8     18.5
9     15.5
10    14.5
11    30.0
12    12.5
Name: Age, dtype: float64

In [379]:
df['Age'].mod(2)

0     1
1     0
2     0
3     0
4     1
5     1
6     1
7     0
8     1
9     1
10    1
11    0
12    1
Name: Age, dtype: int64

In [380]:
df[df['Age'].ge(35)]

   Full Name  Age    City    Salary        Date Category Age Category
0      Alice   45  London  95445.00  2023-01-01        X   Middle Age
1        Bob   58   India  86235.00  2023-01-02        Y       Senior
2        Ash   60   Tokyo  62330.00  2023-01-03        Z       Senior
4        Eva   49  Berlin  65999.00  2023-01-05        Y   Middle Age
5      Frank   67   Paris  88320.00  2023-01-06        X       Senior
6      Grace   45  Berlin  57141.00  2023-01-07        Z   Middle Age
7     Hannah   60  London  65413.00  2023-01-08        Y       Senior
8       Ivan   37   Tokyo  87016.00  2023-01-09        X   Middle Age
11    Hannah   60  London  70425.23  2023-01-08        Y       Senior

In [381]:
df['Category'].value_counts().index

Index(['Y', 'X', 'Z'], dtype='object', name='Category')

In [382]:
df['Category'].value_counts().values

array([6, 5, 2])

In [383]:
df[df['Category'] == "X"]

   Full Name  Age       City   Salary        Date Category Age Category
0      Alice   45     London  95445.0  2023-01-01        X   Middle Age
3      David   28      Paris  46022.0  2023-01-04        X        Adult
5      Frank   67      Paris  88320.0  2023-01-06        X       Senior
8       Ivan   37      Tokyo  87016.0  2023-01-09        X   Middle Age
12    Deepak   25  Bengalore  60000.0  2025-07-30        X        Adult

In [429]:
# Set pandas to display float values in decimal format
#pd.set_option('display.float_format', '{:.2f}'.format)

In [384]:
df.groupby('Category')['Salary'].max()

Category
X    95445.0
Y    86235.0
Z    62330.0
Name: Salary, dtype: float64

In [385]:
city_salary = df.groupby('City')['Salary'].sum()
city_salary

City
Bengalore     60000.00
Berlin       180281.00
India        144960.00
London       231283.23
Paris        134342.00
Tokyo        149346.00
Name: Salary, dtype: float64

In [386]:
city_salary.index

Index(['Bengalore', 'Berlin', 'India', 'London', 'Paris', 'Tokyo'], dtype='object', name='City')

In [387]:
city_salary.values

array([ 60000.  , 180281.  , 144960.  , 231283.23, 134342.  , 149346.  ])

In [388]:
df.groupby('City').agg({'Age':'mean'})

            Age
City
Bengalore  25.0
Berlin     41.0
India      44.5
London     55.0
Paris      47.5
Tokyo      48.5

In [389]:
df.groupby(['Category','Age Category']).agg({"Salary":"sum"}).sort_values(by='Salary', ascending=False).reset_index()

  Category Age Category     Salary
0        Y       Senior  222073.23
1        X   Middle Age  182461.00
2        Y        Adult  115866.00
3        X        Adult  106022.00
4        X       Senior   88320.00
5        Y   Middle Age   65999.00
6        Z       Senior   62330.00
7        Z   Middle Age   57141.00

In [390]:
df.groupby(['Category','Age Category']).agg({"Salary":"sum", "Age":'mean'}).reset_index()

  Category Age Category     Salary        Age
0        X        Adult  106022.00  26.500000
1        X   Middle Age  182461.00  41.000000
2        X       Senior   88320.00  67.000000
3        Y        Adult  115866.00  30.000000
4        Y   Middle Age   65999.00  49.000000
5        Y       Senior  222073.23  59.333333
6        Z   Middle Age   57141.00  45.000000
7        Z       Senior   62330.00  60.000000

In [391]:
category_salary_age = df.groupby('Age Category').agg({"Salary":["min", "max"], "Age":["min", "max"]})
category_salary_age

               Salary          Age
                  min      max min max
Age Category
Adult         46022.0  60000.0  25  31
Middle Age    57141.0  95445.0  37  49
Senior        62330.0  88320.0  58  67

In [392]:
category_salary_age.unstack()

             Age Category
Salary  min  Adult           46022.0
             Middle Age      57141.0
             Senior          62330.0
        max  Adult           60000.0
             Middle Age      95445.0
             Senior          88320.0
Age     min  Adult              25.0
             Middle Age         37.0
             Senior             58.0
        max  Adult              31.0
             Middle Age         49.0
             Senior             67.0
dtype: float64

In [ ]:
Numarical = df.select_dtypes(include=['int', 'float']).columns.tolist()
Categorical = df.select_dtypes(exclude=['int', 'float']).columns.tolist()
print("Numerical Columns: ", Numarical)
print("Categorical Columns: ", Categorical)

### **Merging and Joining**

In [393]:
left_data = {
    'ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 28, 24],
}

left_df = pd.DataFrame(left_data)

# Sample data for right DataFrame
right_data = {
    'ID': [1, 2, 4, 5, 6],
    'City': ['New York', 'London', 'Paris', 'Berlin', 'Tokyo'],
    'Salary': [60000, 75000, 62000, 57000, 80000],
}

right_df = pd.DataFrame(right_data)

In [394]:
left_df

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   28
4   5      Eva   24

In [395]:
right_df

   ID      City  Salary
0   1  New York   60000
1   2    London   75000
2   4     Paris   62000
3   5    Berlin   57000
4   6     Tokyo   80000

In [396]:
data3 = pd.merge(left_df, right_df, on='ID') ## defult inner join
data3

   ID   Name  Age      City  Salary
0   1  Alice   25  New York   60000
1   2    Bob   30    London   75000
2   4  David   28     Paris   62000
3   5    Eva   24    Berlin   57000

In [397]:
inner_join = pd.merge(left_df, right_df, on='ID', how='inner')
inner_join

   ID   Name  Age      City  Salary
0   1  Alice   25  New York   60000
1   2    Bob   30    London   75000
2   4  David   28     Paris   62000
3   5    Eva   24    Berlin   57000

In [398]:
outer_join = pd.merge(left_df, right_df, on='ID', how ='outer') 
outer_join

   ID     Name   Age      City   Salary
0   1    Alice  25.0  New York  60000.0
1   2      Bob  30.0    London  75000.0
2   3  Charlie  35.0       NaN      NaN
3   4    David  28.0     Paris  62000.0
4   5      Eva  24.0    Berlin  57000.0
5   6      NaN   NaN     Tokyo  80000.0

In [399]:
left_join = pd.merge(left_df, right_df, on='ID', how ='left') 
left_join

   ID     Name  Age      City   Salary
0   1    Alice   25  New York  60000.0
1   2      Bob   30    London  75000.0
2   3  Charlie   35       NaN      NaN
3   4    David   28     Paris  62000.0
4   5      Eva   24    Berlin  57000.0

In [400]:
right_join = pd.merge(left_df, right_df, on='ID', how ='right') 
right_join

   ID   Name   Age      City  Salary
0   1  Alice  25.0  New York   60000
1   2    Bob  30.0    London   75000
2   4  David  28.0     Paris   62000
3   5    Eva  24.0    Berlin   57000
4   6    NaN   NaN     Tokyo   80000

### **Pivote Table**

In [401]:
df.pivot_table(index='City', columns='Age Category', values='Salary', aggfunc='sum')

Age Category    Adult  Middle Age     Senior
City
Bengalore     60000.0         NaN        NaN
Berlin        57141.0    123140.0        NaN
India         58725.0         NaN   86235.00
London            NaN     95445.0  135838.23
Paris         46022.0         NaN   88320.00
Tokyo             NaN     87016.0   62330.00

In [402]:
df.pivot_table(index='Full Name', columns='Category', values='Age', aggfunc='mean')

Category      X     Y     Z
Full Name
Alice      45.0   NaN   NaN
Ash         NaN   NaN  60.0
Bob         NaN  58.0   NaN
David      28.0   NaN   NaN
Deepak     25.0   NaN   NaN
Eva         NaN  49.0   NaN
Frank      67.0   NaN   NaN
Grace       NaN  29.0  45.0
Hannah      NaN  60.0   NaN
Ivan       37.0   NaN   NaN
Jack        NaN  31.0   NaN

In [403]:
cross_tab = pd.crosstab(index=df['Full Name'], columns=df['Category'], values=df['Salary'], aggfunc='sum')
cross_tab

Category         X          Y        Z
Full Name
Alice      95445.0        NaN      NaN
Ash            NaN        NaN  62330.0
Bob            NaN   86235.00      NaN
David      46022.0        NaN      NaN
Deepak     60000.0        NaN      NaN
Eva            NaN   65999.00      NaN
Frank      88320.0        NaN      NaN
Grace          NaN   57141.00  57141.0
Hannah         NaN  135838.23      NaN
Ivan       87016.0        NaN      NaN
Jack           NaN   58725.00      NaN

### **Time Series Analysis**

In [404]:
from datetime import datetime

In [405]:
today = datetime.now()
today

datetime.datetime(2025, 7, 31, 12, 48, 58, 521328)

In [406]:
today.year

2025

In [407]:
today.month

7

In [408]:
today.day

31

In [409]:
today.hour

12

In [410]:
date = today.strftime('%Y-%m-%d')
date

'2025-07-31'

In [411]:
date = today.strftime('%A %d-%m-%Y')
date

'Thursday 31-07-2025'

In [412]:
date = today.strftime('%a %d-%m-%Y')
date

'Thu 31-07-2025'

In [413]:
date = today.strftime('%a %d-%B-%Y')
date

'Thu 31-July-2025'

In [414]:
date = today.strftime('%a %d-%b-%Y')
date

'Thu 31-Jul-2025'

In [415]:
df.columns

Index(['Full Name', 'Age', 'City', 'Salary', 'Date', 'Category',
       'Age Category'],
      dtype='object')

In [416]:
df.Date.dtype

dtype('O')

In [417]:
pd.to_datetime(df['Date']).dt.year

0     2023
1     2023
2     2023
3     2023
4     2023
5     2023
6     2023
7     2023
8     2023
9     2023
10    2023
11    2023
12    2025
Name: Date, dtype: int32

In [418]:
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')
df['Date'] = pd.DatetimeIndex(df['Date'])
df['Date']

0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
4    2023-01-05
5    2023-01-06
6    2023-01-07
7    2023-01-08
8    2023-01-09
9    2023-01-10
10   2023-01-07
11   2023-01-08
12   2025-07-30
Name: Date, dtype: datetime64[ns]

In [419]:
df['Date'].dt.year

0     2023
1     2023
2     2023
3     2023
4     2023
5     2023
6     2023
7     2023
8     2023
9     2023
10    2023
11    2023
12    2025
Name: Date, dtype: int32

In [420]:
df['Date'].dt.month

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    7
Name: Date, dtype: int32

In [421]:
df['Date'].dt.day

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10     7
11     8
12    30
Name: Date, dtype: int32

In [422]:
df['Year_Gap'] = today.year - df['Date'].dt.year

In [423]:
df

,Full Name,Age,City,Salary,Date,Category,Age Category,Year_Gap
0,Alice,45,London,95445.00,2023-01-01,X,Middle Age,2
1,Bob,58,India,86235.00,2023-01-02,Y,Senior,2
2,Ash,60,Tokyo,62330.00,2023-01-03,Z,Senior,2
3,David,28,Paris,46022.00,2023-01-04,X,Adult,2
4,Eva,49,Berlin,65999.00,2023-01-05,Y,Middle Age,2
5,Frank,67,Paris,88320.00,2023-01-06,X,Senior,2
6,Grace,45,Berlin,57141.00,2023-01-07,Z,Middle Age,2
7,Hannah,60,London,65413.00,2023-01-08,Y,Senior,2
8,Ivan,37,Tokyo,87016.00,2023-01-09,X,Middle Age,2
9,Jack,31,India,58725.00,2023-01-10,Y,Adult,2
10,Grace,29,Berlin,57141.00,2023-01-07,Y,Adult,2
11,Hannah,60,London,70425.23,2023-01-08,Y,Senior,2
12,Deepak,25,Bengalore,60000.00,2025-07-30,X,Adult,0

In [424]:
present_date = pd.date_range(start='31-07-2025', periods=13, freq='M')
present_date

DatetimeIndex(['2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31',
               '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28',
               '2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30',
               '2026-07-31'],
              dtype='datetime64[ns]', freq='ME')

In [425]:
present_date = pd.date_range(start='31-07-2025', periods=13, freq='y')
present_date

DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31',
               '2029-12-31', '2030-12-31', '2031-12-31', '2032-12-31',
               '2033-12-31', '2034-12-31', '2035-12-31', '2036-12-31',
               '2037-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

In [426]:
present_date = pd.date_range(start='31-07-2025', periods=13, freq='d')
present_date

DatetimeIndex(['2025-07-31', '2025-08-01', '2025-08-02', '2025-08-03',
               '2025-08-04', '2025-08-05', '2025-08-06', '2025-08-07',
               '2025-08-08', '2025-08-09', '2025-08-10', '2025-08-11',
               '2025-08-12'],
              dtype='datetime64[ns]', freq='D')

In [427]:
import calendar
print(calendar.month(2025,8))

    August 2025
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31

In [428]:
calendar.prcal(2026)

                                  2026

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
          1  2  3  4                         1                         1
 5  6  7  8  9 10 11       2  3  4  5  6  7  8       2  3  4  5  6  7  8
12 13 14 15 16 17 18       9 10 11 12 13 14 15       9 10 11 12 13 14 15
19 20 21 22 23 24 25      16 17 18 19 20 21 22      16 17 18 19 20 21 22
26 27 28 29 30 31         23 24 25 26 27 28         23 24 25 26 27 28 29
                                                    30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                   1  2  3       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       4  5  6  7  8  9 10       8  9 10 11 12 13 14
13 14 15 16 17 18 19      11 12 13 14 15 16 17      15 16 17 18 19 20 21
20 21 22 23 24 25 26      18 19 20 21 22 23 24      22 23 24 25 26 27 28
27 28 29 30               25 26 27 28 29 30 31      29 30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2          1  2  3  4  5  6
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       7  8  9 10 11 12 13
13 14 15 16 17 18 19      10 11 12 13 14 15 16      14 15 16 17 18 19 20
20 21 22 23 24 25 26      17 18 19 20 21 22 23      21 22 23 24 25 26 27
27 28 29 30 31            24 25 26 27 28 29 30      28 29 30
                          31

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
          1  2  3  4                         1          1  2  3  4  5  6
 5  6  7  8  9 10 11       2  3  4  5  6  7  8       7  8  9 10 11 12 13
12 13 14 15 16 17 18       9 10 11 12 13 14 15      14 15 16 17 18 19 20
19 20 21 22 23 24 25      16 17 18 19 20 21 22      21 22 23 24 25 26 27
26 27 28 29 30 31         23 24 25 26 27 28 29      28 29 30 31
                          30